### ISSUE TITLE
Storyboard Example

### ISSUE THREAD

**Issue by zehrer** [appsquickly/Typhoon#223]
I try to understand the storyboard feature:
https://github.com/typhoon-framework/Typhoon/wiki/Obtaining-Built-Components#typhoonstoryboard

To be honest it make no sense for me, because according the [View Controller Guide for iOS](https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/ViewControllerPGforiOS.pdf) when application:didFinishLaunchingWithOptions: is called the following steps are already done:
- self.window is already set (if defined)
- storyboard is loaded 
- rootViewController is alreay set. 

Expected here is only "our app delegate is expected to configure the initial view controller". 

In this case i would expect just some injections (e.g. the Assembly) into the root view controller. Maybe further stuff with the storyboard.

Why again loading the storyboard?
Why again setup the rootViewController?

**Comment by reallyseth** [comment]
Did you create a storyboard example app? I'd be interested in seeing it.

**Comment by jasperblues** [comment]
@reallyseth The <a href="https://github.com/appsquickly/Typhoon-CoreData-RAC-Example">Typhoon + Core Data + RAC</a> sample uses storyboards, but a better example would: 

* Show only storyboards
* Include an example of autoinjections

I plan to write one ASAP to use as a mobile tuts tutorial. In the meantime, I'm happy to help you one-on-one with any queries you have.

**Comment by reallyseth** [comment]
Thanks Jasper! After searching around I’ve been able to get storyboards with autoinjections working. But if I hit any questions, I’ll send you a note.
