### ISSUE TITLE
Typhoon Needs Documentation Pages

### ISSUE THREAD

**Issue by swizzlr** [appsquickly/Typhoon#244]
I can't generate the documentation with Doxygen, but I am inexperienced with the tool – I found this http://jasperblues.github.io/Typhoon/api/index.html but it looks out of date by many months. Is there a script I'm missing, or could it be added to the website?

**Comment by lisacmer** [comment]
unfortunately http://www.typhoonframework.org/ is unavailable at the moment.

**Comment by jasperblues** [comment]
The website now runs at: http://appsquickly.github.io/Typhoon . . not sure if the build server still produces docs there though.
