### ISSUE TITLE
TyphoonAssemblyActivator

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#253]
Users can still use this class if they wish. However: 

**Drivers**

* TyphoonComponentFactory is an extra concept that needs to be learned and read in the documentation. This doesn't need to be the case. 
* TyphoonComponentFactory being public API increases cost + overhead in maintaining the docs. Especially as we now have Swift version and ObjC version. 
* Casting between factory and assembly does not work in Swift. 

**Implementation:**

Add the following to Typhoon assembly: 

```objc

/*
* Returns NO. Facade to the TyphoonComponentFactory method (which returns YES). 
*/
@property(nonatomic, readonly) BOOL isBuilt; 

/**
* Raises 'not built' exception. Facade to the TyphoonComponentFactory method 
*/
- (id) componentForType:(id)classOrProtocol; 
```

**Create the following class:**

```objc
@interface TyphoonAssemblyActivator

@property(nonatomic, copy, readonly) NSArray *assemblies; 

- (instancetype) initWithAssemblies:(NSArray *)assemblies; 

- (void) build;

@end
```

The build method will cause the array of non-built assemblies to be replaced with built assemblies. 

* Before using TyphoonAssemblyActivator, TyphoonAssembly returns TyphonDefinitions (recipes to build instnaces). 
* After using TyphoonAssemblyActivator, the assembly returns actual built instances. 
* Everything with TyphoonComponentFactory happens behind the scenes. 
* No issues with casting in Swift.

**Comment by alexgarbarev** [comment]
Reviewed.
:+1: Nice work!
