### ISSUE TITLE
factory.componentForType(aProtocol) does not work in Swift

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#256]

**Comment by jasperblues** [comment]
This may be because the protocol wasn't marked with `@objc`

**Comment by jasperblues** [comment]
Doesn't work even for `@objc` protocols.

**Comment by etolstoy** [comment]
We strongly recommend to use the [pure Swift version](https://github.com/appsquickly/TyphoonSwift) of Typhoon.

**Comment by jasperblues** [comment]
Perhaps we can make it more clear Typhoon Swift is ready for heavy use in the Readme.
