### ISSUE TITLE
TyphoonConfigPostProcessor: only one config is used, no matter how many of them are present

### ISSUE THREAD

**Issue by gumanoid** [appsquickly/Typhoon#263]
This is actually a silly kind of pull request :)

Setup:
- Typhoon 2.3.0
- single root assembly with several collaborating ones
- each assembly has it's own .plist file, indicating that through:

```objective-c
- (id)config
{
    return [TyphoonDefinition configDefinitionWithName:@"some.plist"];
}
```

Expected: all values from all configs are available for injection through `TyphoonConfig(@"some.key")`
Actual: I can inject values only from one config

Reason: `TyphoonConfigPostProcessor` overrides all `TyphoonInjectionByConfig` instances. In the case described, there are several `TyphoonConfigPostProcessor`s. Thus, the last applied `TyphoonConfigPostProcessor` overrides values from other configs with nil objects.

Solution/workaround: In `TyphoonConfigPostProcessor`, check whether it contains value for the config key, and if it doesn't, just skip corresponding `TyphoonInjectionByConfig` instance.
This can be done by replacing this code in TyphoonConfigPostProcessor.m:

```objective-c
#pragma mark - Protocol Methods

- (void)postProcessComponentFactory:(TyphoonComponentFactory *)factory
{
    for (TyphoonDefinition *definition in [factory registry]) {
        [definition enumerateInjectionsOfKind:[TyphoonInjectionByConfig class] options:TyphoonInjectionsEnumerationOptionAll
                                   usingBlock:^(TyphoonInjectionByConfig *injection, id *injectionToReplace, BOOL *stop) {
            injection.configuredInjection = [self injectionForConfigInjection:injection];
        }];
    }
}

- (id<TyphoonInjection>)injectionForConfigInjection:(TyphoonInjectionByConfig *)injection
{
    id value = [self configurationValueForKey:injection.configKey];
    id<TyphoonInjection>result = nil;

    if ([value isKindOfClass:[NSString class]]) {
        result = TyphoonInjectionWithObjectFromString(value);
    } else {
        result = TyphoonInjectionWithObject(value);
    }

    return result;
}
```

with this code:

```objective-c
#pragma mark - Protocol Methods

- (void)postProcessComponentFactory:(TyphoonComponentFactory *)factory
{
    for (TyphoonDefinition *definition in [factory registry]) {
        [definition enumerateInjectionsOfKind:[TyphoonInjectionByConfig class] options:TyphoonInjectionsEnumerationOptionAll
                                   usingBlock:^(TyphoonInjectionByConfig *injection, id *injectionToReplace, BOOL *stop) {
            id configuredInjection = [self injectionForConfigInjection:injection];
            if (configuredInjection) {                 //<---  SOLUTION part 1
                injection.configuredInjection = configuredInjection;
            }
        }];
    }
}

- (id<TyphoonInjection>)injectionForConfigInjection:(TyphoonInjectionByConfig *)injection
{
    id value = [self configurationValueForKey:injection.configKey];
    id<TyphoonInjection>result = nil;

    if ([value isKindOfClass:[NSString class]]) {
        result = TyphoonInjectionWithObjectFromString(value);
    } else if (value) {                 //<---  SOLUTION part 2
        result = TyphoonInjectionWithObject(value);
    }

    return result;
}
```

**Comment by igrekde** [comment]
It seems that @mbaltaks has already implemented the global config attaching in `TyphoonStartup.m`. It either looks for `TyphoonConfigFilename` key in the `Info.plist`, or looks for `config_%@.plist` file in the main bundle, where `%@` is a bundle identifier.

This approach seems fine, but I have the following suggestions:

- It would be more flexible to store an array of configs under a `TyphoonConfigFilename` key - the configs contents can be completely unrelated, but require global scope. This solution should be backwards compatible, so maybe it'd make sence to introduce another key - `TyphoonConfigFilenames` and to deprecate the previous one.
- We should definitely document this feature - a couple of my colleagues asked for this already - and we didn't know, that it's implemented already :)

**Comment by igrekde** [comment]
Updated documentation about `TyphoonConfig` usage: https://github.com/appsquickly/Typhoon/wiki/What-can-be-Injected
