### ISSUE TITLE
Demo on adding Typhoon to an existing/empty Xcode project

### ISSUE THREAD

**Issue by RobBrennan** [appsquickly/Typhoon#276]
I was able to get the sample app up and running, but it's unclear how I would add Typhoon to an existing or a new Xcode project. The Podfile from the example app does not install under Xcode 6.1 and Yosemite 10.10 (previous issue), and the getting started guide skips right over incorporating it into an existing project.

**Comment by jasperblues** [comment]
Let's close this off so that we can focus on Typhoon 3.0 features. Would love if someone has an interest in picking it up again.

**Comment by sebastianwr** [comment]
Yes, guess that makes sense since I haven't had the time to do this properly yet. I'll get back to you if I'll have some spare time in the future.

**Comment by jasperblues** [comment]
@sebastianwr You are welcome any time. Thanks for all your efforts so far.

**Comment by jasperblues** [comment]
Hello @RobBrennan 

Here's a tutorial set from @JeffBNimble : https://www.youtube.com/playlist?list=PLhU81D62nv-Yd5jCW9LRjI4_AfI5NwJhe

It doesn't go deeply into integration of Typhoon in legacy projects, but hopefully enough to get things moving. Lately we've been seeing a new tutorial every week or so, which is encouraging.
