### ISSUE TITLE
Swift: Propagating run-time arguments through to dependencies

### ISSUE THREAD

**Issue by robbiebubble** [appsquickly/Typhoon#277]
hi all,

i would like to achieve the following in swift but i don't know how. would you mind to provide an example in swift? 
[Propagating run-time arguments through to dependencies](https://github.com/typhoon-framework/Typhoon/wiki/Propagating%20runtime%20arguments#propagating-run-time-arguments-through-to-dependencies) 

thx a lot!

**Comment by jasperblues** [comment]
As far as I know this all works on recent versions of Typhoon/Swift.

**Comment by jasperblues** [comment]
Closing as obsolete. Reopen if necessary.
