### ISSUE TITLE
No newline at end of file

### ISSUE THREAD

**Issue by yifeic** [appsquickly/Typhoon#304]
TyphoonDefinition.h:276:5: No newline at end of file

I am having this error in my project after import "TyphoonAssembly.h".

**Comment by jasperblues** [comment]
Oops. Looks like AppCode doesn't add these by default. Will fix. 

Meanwhile, this error occurs if you have "treat warnings as errors" enabled. You can still have this setting, but turn of this specific warning.

**Comment by yifeic** [comment]
Thanks!
For anyone who also needs it, here is how I turn off specific warnings.
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-interface-ivars"
#pragma clang diagnostic ignored "-Wassign-enum"
#pragma clang diagnostic ignored "-Wnewline-eof"
#import "TyphoonAssembly.h"
#pragma clang diagnostic pop
```
