### ISSUE TITLE
Guidance on objects being instantiated before application:didFinishLaunchingWithOptions:... where, when, or how should services be set up?

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#308]
Many services offer iOS SDKs that require the app to set the SDK up with a one-line class method call early in the application. e.g.: [Parse](https://parse.com)'s initialization looks like: `[Parse setApplicationId:@"<your app id>" clientKey:@"<your client key>"];`.

These often go into the `-application:didFinishLaunchingWithOptions:` method of your `XXAppDelegate`.

When using Typhoon, it sometimes makes sense to inject components that make use of these services. The problem is, it's possible that these components are instantiated before `-application:didFinishLaunchingWithOptions:` even has a chance to execute. For instance:

```objc
@interface MYAppDelegate ()
@property(nonatomic, strong) InjectedClass(MYComponentThatNeedsParseSetUpBeforeInitialization)component;  // !!! calls to Parse made before Parse is ready
@end

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    [Parse setApplicationId:@"<your app id>" clientKey:@"<your client key>"];

    // Parse is ready here.
    
    return YES;
}
```

So officially, where should these calls go instead?

**Comment by jasperblues** [comment]
We could debate creating a hook for this in either the `AppDelegate`:

```objc
- (void)typhoonWillStartUp; //for want of a better name
```

 or `TyphoonAssembly`: 

```objc
- (void)assemblyWillAssemble; //or something
```

but what I currently do is create a category on the framework class and use: 

```objc
[definition performBeforeInjections:SEL];
```

If you wish you can use `performBeforeInjections:parameters` and have the parameters come from `TyphoonConfig`

**Comment by alexgarbarev** [comment]
another options:
1) Create some "wrapper" for Parse static calls (for example ParseManager or something), then create definition for that wrapper with singletone scope - after you can inject that wrapper into your component that need Parse. (i.e. explicit dependency) 

<-- Useful when not too much objects requiers parse at startup


2) Create definition for class that conforms to TyphoonDefinitionPostProcessor. This definition would be registered as factory "post-processor". All "post-processors" runs at very start, before singletons creation.
Then you can do all your configurations that need to performs at very start inside `postProcessDefinitionsInFactory:` method

<-- Harder to read and understand (implicit) but usefull when too much objects requires one dependency (for example logging system like cocoalumberjack)

**Comment by jasperblues** [comment]
And one other existing way folks do this is create a definition that uses `@selector(class)` as its initializer. Eg: 

```objc
- (id)loggers
{
    return [TyphoonDefinition withClass:[DDLog class] configuration:^(TyphoonDefinition *definition) {
        [definition useInitializer:@selector(class)];
        [definition injectMethod:@selector(addLogger:) parameters:^(TyphoonMethod *method) {
            [method injectParameterWith:[self ttyLogger]];
        }];
        definition.scope = TyphoonScopeSingleton;
    }];
}
```
This definition above has singleton scope, so will be run on startup. It won't be guaranteed to run first though, so take care. (Subsequent components that depend on this could have `TyphoonScopeLazySingleton`, `TyphoonScopeWeakSingleton`, `TyphoonScopeObjectGraph` (default) or `TyphoonScopePrototype`). 

**Questions:**

* Given all of these approaches do we need a standard approach? Or is it OK to be creative? Perhaps extract a wiki page and link it from the 'configuration' section of *What can be Injected* ? 
* Will the hooks suggested above add more value than the complexity they introduce?

**Comment by fatuhoku** [comment]
@jasperblues Thanks for the response. I'll try the latter approach out. I'm comfortable declaring `[Parse class]` as singleton. It works best with my mental model of Typhoon. It is a bit strange of course, given that Typhoon focusses on handling objects and configuring instances as opposed to `Class` objects.

**Comment by jasperblues** [comment]
Which to people like: 

```objc
- (void)typhoonWillStartUp; //for want of a better name
``

or TyphoonAssembly:

```objc
- (void)assemblyWillAssemble; //or something
```

or The way shown above using the 'class' as the initializer along with the ability to set order or instantiation? 

My preference is the 2nd: `asssemblyWillAssemble`

**Comment by fatuhoku** [comment]
Yeah I imagine the latter is better. Parse is a dependency; and therefore falls under the remit of — guess what — a dependency injection framework like Typhoon!

So I actually see that Typhoon will recommend not one, but two potential implementation options:

1. the super-quick **cut-and-paste solution**: `-assemblyWillAssemble` execute prior to instantiating any components in that assembly. Paste code from `-application:didFinishLaunchingWithOptions:` and we are done. **Fantastic**. The downside to this implementation is of course that API key's and other bits of configuration can't get injected.

2. the "But I want DI to inject my configuration, dude" solution:  so if the developer is bothered enough then they can use the `[definition useInitializer:@selector(class)];` approach

I would stress that both options need to be clearly documented so that the developer has a chance of picking and choosing what's suitable for them at the time. The second option is the 'correct' way to set it up, but requires knowledge of Typhoon and is premature abstraction.



 into the call. I can imagine using preprocessor macros inside of  `-assemblyWillAssemble`:

```
NSString *apiKey
#ifndef DEBUG
apiKey = @"PRODUCTION";
#else
apiKey = @"PRODUCTION";
#end
[Service setUpServiceWithApiKey:apiKey];
```

This works just fine, of course. I think `-assemblyWillAssemble` could be an answer.

In the ideal world DI should be used to inject API keys as well. . This needs documenting.

What do you think @jasperblues?

**Comment by alexgarbarev** [comment]
@fatuhoku 
The problem with `[definition useInitializer:@selector(class)];` solution is that you cannot control when time when it's performed. I had that problem using this approach, some of my singletones tries to use logging system which was not initialized yet. 

Maybe we can extend API or something... After that we could recomment that as 'correct' approach

**Comment by jasperblues** [comment]
* Having eg `[definition setIntantiationPriority:1]; //default is 100` . . allows fine grained control but is messy since it would only apply to singletons. Would have to raise error in an attempt to use this for non-singleton. In retrospect it might've been nice if we had sub-class per scope. eg `TyphoonObject` (default), `TyphoonPrototype` , `TyphoonSingleton` . . this would allow specific properties for that type. 
* Introducing `TyphoonScopeEagerSingleton` could work.

**Comment by alexgarbarev** [comment]
Finally I think using `assemblyWillAssemble` is more obvous is easy to use solution because using priorities is too implicit - hard to read and understand the order.. Also that makes dependencies implicit and hard to understand too. 

I prefer these two options:
1) Make wrapper (as I told in my first answer in this thread) - that makes dependencies explicit
2) Make `assemblyWillAssemble` or anything similar - some peice of code that guaranteed to be peformed at start. That makes dependencies implicit but easy to understand, since all in once place

**Comment by jasperblues** [comment]
@fatuhoku Would you like push access to help clean up the documentation? It would be really helpful, since the challenges you faced getting started with Typhoon (current features) are still fresh in mind. Meanwhile, you've been involved in discussions on future features.

**Comment by fatuhoku** [comment]
@jasperblues Yeah I'm not objected to that. I would love to contribute what I know of Typhoon in the form of documentation. I intend to slowly refactor my application to make use of it.

**Comment by jasperblues** [comment]
@fatuhoku granted. We really appreciate your help. Its nice to meet someone who cares about good documentation. As it stands now Typhoon is helpful for folks are very familiar with Di from other languages. We'd really like if the documentation was good enough for all folks to benefit.

**Comment by jasperblues** [comment]
Please let us know if you make changes so that we can review the technical accuracy and give feedback.

**Comment by fatuhoku** [comment]
@jasperblues Sure thing. I'll do this on a need-by-need basis. Got a slightly different focus right now!

**Comment by jasperblues** [comment]
@fatuhoku I just faced this issue too. Cheated by hooking `resolveCollaboratingAssemblies`

**Comment by fatuhoku** [comment]
@jasperblues Ah, look at you, hooking into all those undocumented methods ;)

**Comment by alexgarbarev** [comment]
I found that `init` method on AppDelegate works perfectly on our needs, like this:

```objc
@implementation AppDelegate

- (instancetype)init
{
    self = [super init];
    if (self) {
        [self setupLogging];
    }
    return self;
}
```

The lifecycle is:
1. main.m
2. UIApplication creation
3. AppDelegate creation <-- init method called here
4. UIApplication setDelegate called <-- Typhoon created here
5. UI Loading
6. Application did finish launching called

**Comment by jasperblues** [comment]
I wondered if it still might be beneficial to create the life-cycle method? This would communicate intention to folks. Alternatively we can just add API doc to init, saying it can be safely overridden.

**Comment by fatuhoku** [comment]
Fantastic. I think that has to be the most straightforward solution of all...

**Comment by jasperblues** [comment]
Once the docs have been done, let's badge as 'Ready for Review'. After that we can close off the ticket.

**Comment by jasperblues** [comment]
NB, if you add API docs to any Typhoon classes, and commit, they'll turn up on www.typhoonframework.org/docs/latest/api after a few minutes.

**Comment by joshavant** [comment]
Hi all... I encountered this problem in my project, and I'm trying to figure out how the solution @alexgarbarev discussed works?

We're using plist integration, since our entire app relies on Storyboards. With that configuration, we'd like to find a solution to inject a dependency into the AppDelegate (for use during `application:didFinishLaunchingWithOptions:`).

Would @alexgarbarev's solution work for this? If so, do you think you could provide some elaboration?

Thank you!
