### ISSUE TITLE
Xcode 6 + Cocoapods 0.36.0.beta.1: Too many arguments to function call, expected 0, have 2; Enable Strict Checking of objc_msgSend Calls should be set to NO 

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#311]
Copied from [issue on Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/3060).
- - - - - - 

Lots of pods use `objc_msgSend`. Compiling these pods with causes the following error message:

```
.../Pods/Typhoon/Source/Factory/Block/TyphoonAssemblyDefinitionBuilder.m:198:29: Too many arguments to function call, expected 0, have 2
```

Is there a sensible way to avoid this problem for all of your pods the maintainers each patch it? Perhaps there should be a directive in the Podfile that lets the user turn off the `Strict Checking` option in Xcode.

![screen shot 2015-01-21 at 22 26 55](https://cloud.githubusercontent.com/assets/430233/5846790/b2403618-a1be-11e4-8154-44d03f36e35f.png)

**Comment by jasperblues** [comment]
PR #305 should have addressed all these. Still having a problem?

**Comment by fatuhoku** [comment]
Ah. No — I don't use master, so I haven't got the fix yet. Thanks.
