### ISSUE TITLE
TyphoonStoryboard.m has incorrect method

### ISSUE THREAD

**Issue by newonder** [appsquickly/Typhoon#313]
In method below you support only three types of containers

```objective-c
- (void)injectPropertiesForViewController:(UIViewController *)viewController
{
    if (viewController.typhoonKey.length > 0) {
        [self.factory inject:viewController withDefinition:NSSelectorFromString(viewController.typhoonKey)];
    }
    else {
        [self.factory inject:viewController];
    }

    if ([viewController isKindOfClass:[UINavigationController class]]) {
        for (UIViewController *controller in ((UINavigationController *) viewController).viewControllers) {
            [self injectPropertiesForViewController:controller];
        }
    }

    if ([viewController isKindOfClass:[UITabBarController class]]) {
        for (UIViewController *controller in ((UITabBarController *) viewController).viewControllers) {
            [self injectPropertiesForViewController:controller];
        }
    }
    
    if ([viewController isKindOfClass:[UISplitViewController class]]) {
        for (UIViewController *controller in ((UISplitViewController *) viewController).viewControllers) {
            [self injectPropertiesForViewController:controller];
        }
    }
}
```

But user can make custom containers so we suggest another realisation: 

```objective-c
- (void)injectPropertiesForViewController:(UIViewController *)viewController
{
    if (viewController.typhoonKey.length > 0) {
        [self.factory inject:viewController withDefinition:NSSelectorFromString(viewController.typhoonKey)];
    }
    else {
        [self.factory inject:viewController];
    }

	for (UIViewController *controller in viewController.childViewControllers) {
		[self injectPropertiesForViewController:controller];
	}
}
```

**Comment by jasperblues** [comment]
:+1: Looks good to me. Adds flexibility. Meanwhile the previously supported UINavigationController and UITabBarController do correctly implement UIViewController containement, so all should be well.

**Comment by alexgarbarev** [comment]
Nice idea. Will `viewController.childViewControllers` works perfectly for UISplitViewController, UITabBarController and UINavigationController too?
At the time I wrote that I thought that these containers are only case that use can create in Storyboard (since if user add viewController containment in storyboard (with segues), then it calls instantiateViewControllerWithIdentifier method again)

**Comment by alexgarbarev** [comment]
But if viewController.childViewControllers managed dynamically in code, only array of initial viewController.childViewControllers will be processed. (i.e. after changing that array user must process each new viewController manually) What do you think about it? Maybe it can be cause of error (user will think that everything will be processed automatically)

**Comment by alexgarbarev** [comment]
> Will viewController.childViewControllers works perfectly for UISplitViewController, UITabBarController and UINavigationController too 

If answer is YES, then we'll be happy with your contribution. :-) (Waiting for PR from you)

**Comment by newonder** [comment]
UITabbarViewController and UINavigationController support -(NSArray *)childViewControllers method. I don't know about  UISplitViewController.

Property viewController.childViewControllers is readonly so you must create methods for adding child view controllers.

For example:

```objective-c
-(void)setPublicRootViewController:(UIViewController *)publicRootViewController {
	if (_publicRootViewController) {
		[_publicRootViewController willMoveToParentViewController:nil];
		[_publicRootViewController removeFromParentViewController];
	}
	
	if (publicRootViewController) {
		[self addChildViewController:publicRootViewController];
		[publicRootViewController didMoveToParentViewController:self];
	}
	
	_publicRootViewController = publicRootViewController;
}
```

**Comment by jasperblues** [comment]
Closing as obsolete.

**Comment by newonder** [comment]
Do I understand that the idea of a synthesis of containers discarded? What to do whatever it yet implemented?

**Comment by jasperblues** [comment]
@newonder Sorry, the issue was mistakenly marked with 'wait for reply' . . since there was no reply in quite some time, I closed it. . . reopening. Do you want to send a pull request for this feature?

**Comment by jasperblues** [comment]
Ah I see the reason for 'wait for reply' tag. We to clarify if the proposed change works OK for UISplitViewController

**Comment by newonder** [comment]
As I understand it, is expected to public opinion, if it is important, let's wait for more - if not, let, I will request the change. :)

Theoretically, the UISplitViewController as the subclass of the UIViewController must correctly handle the moment. I can check the other day, I unfortunately do not have projects with such controllers will need to deal with this issue separately.

**Comment by jasperblues** [comment]
As soon as that case is tested we can merge this change in. If you or someone would like to volunteer to undertake that test, it would certainly speed the resolution of this feature.

**Comment by newonder** [comment]
For UISplitViewController all works well, so that the standard controller is good. It remains to make a merge request and a small correction in the code associated with a change in the method signature.

```objective-c
- (void)injectPropertiesForViewController:(UIViewController *)viewController
{
	if (viewController.typhoonKey.length > 0) {
		[self.factory inject:viewController withSelector:NSSelectorFromString(viewController.typhoonKey)];
	}
	else {
		[self.factory inject:viewController];
	}
	
	for (UIViewController *controller in viewController.childViewControllers) {
		[self injectPropertiesForViewController:controller];
	}
}
```

```objective-c
[self.factory inject:viewController withSelector:NSSelectorFromString(viewController.typhoonKey)];
```
instead of the
```objective-c
[self.factory inject:viewController withDefinition:NSSelectorFromString(viewController.typhoonKey)];
```

**Comment by jasperblues** [comment]
:+1:  Sounds good!
