### ISSUE TITLE
Typhoon Option Matcher is not documented

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#317]

**Comment by igrekde** [comment]
The documentation is great, thanks, Jasper! Maybe it's worth to add an additional section about the `-withOption:yes:no:` method?

**Comment by jasperblues** [comment]
OK @igrekde I will add this. Also #390 has been suggested.

**Comment by igrekde** [comment]
@jasperblues Added the section about `withOption:yes:no:` method.

**Comment by jasperblues** [comment]
:+1:
