### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by ronak2121** [appsquickly/Typhoon#323]
Are there any documented release notes on what's new between versions? I've kept looking for them around the site but can't seem to find anything.

**Comment by jasperblues** [comment]
Ah, its subtle ;) You click the pod badge (3.0.1) under Installing in the ReadMe: 

Here : https://github.com/appsquickly/Typhoon/wiki/Change-Log

**Comment by jasperblues** [comment]
NB: You should be able to upgrade (recommended) from 2.x transparently, no code changes required.
