### ISSUE TITLE
Injection with Run-time Arguments Fails with Swift String

### ISSUE THREAD

**Issue by dereekb** [appsquickly/Typhoon#324]
Ran into a bug where when trying to inject with a Swift string instead of a NSString it results in a function call (Foundation._convertNSStringToString) to convert between types which results in the forwardingTargetForSelector: function of TyphoonInjectionByRuntimeArgument being called and crashing program.

Workaround is to instead declare the type as NSString:

```swift

public class Assembly : TyphoonAssembly {

//Causes crash
public dynamic func foo(boo:String) -> AnyObject { ... } 

//Safe
public dynamic func foo(boo:NSString) -> AnyObject { ... } 

}
```

If boo is declared as an NSString before injection, the conversion won't occur.

**Comment by jasperblues** [comment]
Hello @dereekb, 

I'm afraid this is a known limitation and I don't think there's anything we can do about it at this stage. 

Swift doesn't have its own native reflection and by default it uses the less dynamic vtable style dispatch, in contrast to Objective-C's very flexible messaging. Therefore for DI with Typhoon we go via the Objective-C runtime, which can only deal with types that are interoperable between both layers.

**Comment by dereekb** [comment]
Yea I figured as much. Just thought I'd report it incase someone else runs into the issue.

**Comment by jasperblues** [comment]
Thanks @dereekb, we appreciate that. We put the information in the <a href="https://github.com/appsquickly/Typhoon/wiki/Swift-Quick-Start">Swift Quick Start</a>, but if you can remember the place where you expected to find this information (header doc, another wiki, etc) we can also add it there.
