### ISSUE TITLE
[factory registerDefinition:] method is slow

### ISSUE THREAD

**Issue by warnyul** [appsquickly/Typhoon#325]
I has increased the typhoon version in my project to 3.0.1 and the [factory registerDefinition:] will be slower and slower, when the registry array count is increasing. I tried register more than 400 TyphoonDefinitions. The execution time of this method increased to 0.5-0.8 seconds in simulator. Start time of iOS application will be more than 1 minute.

**Comment by jasperblues** [comment]
To harzard a guess, it sounds like a full load/unload cycle is happening for each registration.

**Comment by warnyul** [comment]
Probably true. I am debugging the code. In every case after registerDefinition method has been called, it reloads all registered components and calls the [TyphoonFactoryAutoInjectionPostProcessor postProcessDefinitionsInFactory:] method.

**Comment by alexgarbarev** [comment]
Please try again with `:head` version of Typhoon. If everying fine we'll push new release

**Comment by alexgarbarev** [comment]
Temproary reverted back, since it's fail tests. Have to do some refactoring on Typhoon Core for that. Hope I'll do that soon (maybe at weekends)

**Comment by warnyul** [comment]
I have an tip for optimize the code. I removed some cycles from code. The unit test runs correctly and it will be faster. But I don't understand how solved the circular Dependencies. I uploaded my changes [here](https://github.com/warnyul/Typhoon).

**Comment by jasperblues** [comment]
@alexgarbarev Do you want to review this suggestion?

**Comment by warnyul** [comment]
I updated my solution. I cached the injected properties for classes. In my case this solution loads components about 4,6-4,7 seconds.

**Comment by jasperblues** [comment]
How about send a pull request, and we can try it out on the main branch for a few days, on current projects. If ok, let's push 3.0.3

**Comment by jasperblues** [comment]
Merged to master. Try to find any issues. If all good push 3.0.4

**Comment by warnyul** [comment]
I tested it. It works.

**Comment by jasperblues** [comment]
@warnyul Sorry for delay. This is now available at CocoaPods mater repo as Typhoon 3.1.0
