### ISSUE TITLE
What's the proper way to inject table view cell loaded view registerNib and dequeueReusableCellWithIdentifier?

### ISSUE THREAD

**Issue by leetr** [appsquickly/Typhoon#332]
Sorry, this is not an issue, but I couldn't find a better forum.

What's the proper way to inject table view cell loaded view registerNib and dequeueReusableCellWithIdentifier?
The easiest way I've found is the following, but maybe you have a better way?

    UINib *nib = [UINib nibWithNibName:@"FooCell" bundle:nil];
    [tableView registerNib:nib forCellReuseIdentifier:fooCellIdentifier];
             
    UITableViewCell *fooCell = [tableView dequeueReusableCellWithIdentifier:fooCellIdentifier];

    TyphoonComponentFactory *factory = [TyphoonComponentFactory defaultFactory];
    [factory inject:fooCell];

    return fooCell;

**Comment by jasperblues** [comment]
Here's the correct solution for now: http://stackoverflow.com/a/28620601/404201

In future we might make a shortcut.

**Comment by leetr** [comment]
Thank you

**Comment by jasperblues** [comment]
You're welcome :)

**Comment by bespalown** [comment]
as well as the implementation will be on Swift?
