### ISSUE TITLE
Should be able to attach configurer to assembly before or after activation

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#344]
* Typhoon 3.0 has assembly implementing the `TyphoonComponentFactory` protocol. 
* Before activation these methods raise an exception. 
* After activation they forward to the underlying factory. 

In the the case of attaching a configurer this is not the ideal behavior. Before activation it should register an infrastructure definition for the configurer. This would avoid unload/load of singletons.

**Comment by igrekde** [comment]
I've investigated the problem a bit and see the following decisions:

- We can store all of the pre-attached infrastructure definitions in a separate collection - and return them to the `TyphoonComponentFactory` in the method:
```
- (NSArray *)definitions {
    return [[_definitionBuilder builtDefinitions] arrayByAddingObjectsFromArray:_preattachedInfrastructureDefinitions];
}
```
- We can add new methods to the current assembly in runtime using the `class_addMethod` - and (probably 😄) they would be processed just like the normal ones.

@jasperblues , what's your point?

**Comment by jasperblues** [comment]
> @jasperblues , what's your point?

Do you mean: 

* 'What was the rationale for the feature"? 
* Which approach do I prefer?

**Comment by igrekde** [comment]
@jasperblues The both questions - but mostly the second one.

**Comment by jasperblues** [comment]
I don't recall what my point was. I think while writing an integration test with Typhoon I tried to attach config incorrectly. 

Between the two implementations I think the first is adequate and simpler.
