### ISSUE TITLE
Validate definition and property names don't use Cocoa conventions for new instances

### ISSUE THREAD

**Issue by HiveHicks** [appsquickly/Typhoon#346]
I've set up a simple app using Typhoon, and now I'm getting this exception on every launch. If I enable zombie objects, it says:

```
*** -[TyphoonReferenceDefinition release]: message sent to deallocated instance 0x1700dbdd0
```

The exception is thrown from `-[TyphoonAssemblyDefinitionBuilder populateCache]`.

I've posted a project on BitBucket so that you can debug it: https://bitbucket.org/HiveHicks/cueit

**Comment by jasperblues** [comment]
Thanks for reporting this issue. Have you tried writing any integration tests for the components in your assembly? It would help to isolate where the problem is coming from.

**Comment by HiveHicks** [comment]
No, I didn't. I've written apps before with much more complex and massive assemblies before, and everything worked well there. My current assemblies are extremely basic, still I can't see what I'm doing wrong.

**Comment by jasperblues** [comment]
Let's go through the layers to isolate the problem. You can create an XCTest test case where you start with the bottom layer: 

```objc
CICoreAssembly *assembly = [[CICoreAssembly new] activate];
//Resolve a component from this. 
```

And work up the layers. Until the problem is reproduced.

**Comment by HiveHicks** [comment]
```objective-c
- (void)testFileAssembly
{
    CIFileAssembly *fileAssembly = [[CIFileAssembly assembly] activate];

    XCTAssertEqual([fileAssembly fileManager], [NSFileManager defaultManager]);
}

- (void)testDataAssembly
{
    CIDataAssembly *dataAssembly = [[CIDataAssembly assembly] activateWithCollaboratingAssemblies:@[
            [CIFileAssembly assembly]
    ]];

    XCTAssertNotNil([dataAssembly mainQueueManagedObjectContext]);
    XCTAssertNotNil([dataAssembly newBackgroundManagedObjectContext]);
}

- (void)testCoreAssembly
{
    CICoreAssembly *assembly = [[CICoreAssembly new] activateWithCollaboratingAssemblies:@[
            [CIFileAssembly assembly],
            [CIDataAssembly assembly]
    ]];

    NSNotificationCenter *notificationCenter = [assembly notificationCenter];
    CIMixesUpdater *mixesUpdater = [assembly mixesUpdater];
}
```

First two tests are passing, `testCoreAssembly` throws the exception while activating.

**Comment by jasperblues** [comment]
Thanks for the info. I don't see anything alarming in the Core Assembly. Will have to debug, however, my schedule is tight at the moment. I won't be able to look at it until mid week.

**Comment by HiveHicks** [comment]
That's okay, there is no hurry on my side.

**Comment by HiveHicks** [comment]
Hello!
Did you have any chance to debug this issue?

**Comment by alexgarbarev** [comment]
Hey @HiveHicks, 

I see potential reason of that crash. I think it's because your method started from `new`, by objective-c convension that means that caller is owner of the returned object, and `retainCount` will be decreased by one than usually.

Let's mark this as bug, I think we can do some reseach to handle that error or produce warning for that method names..

For now, try to rename your method (for example `newBackgroundManagedObjectContext` -> `backgroundManagedObjectContext`)

**Comment by HiveHicks** [comment]
@alexgarbarev yeah, seems like this is the reason! I've renamed the method, and everything works now. Thanks!

**Comment by mthole** [comment]
For anyone else wondering about this, you can also specify the Objective-C "method family" in your Assembly's interface to fix this issue, e.g.:

```
@interface MyApplicationAssembly : TyphoonAssembly

- (MYHomeViewController *)newHomeViewController __attribute__((objc_method_family(none)));

@end
```

I made a macro to make it looks a little less ugly.

**Comment by jasperblues** [comment]
@mthole is it possible to query the method family via the ObjC runtime? If so great, otherwise I was thinking we' just apply a rule that prevents using those names.

**Comment by mthole** [comment]
I just spent a few minutes looking into the ObjC runtime, but couldn't find where this information is stored. I may just be looking in the wrong spot, though?

Rather than having Typhoon prevent naming like the above, I'd instead have Typhoon ensure that the actual runtime methods that are generated (haven't dived into the specifics of how this works) meet the implicit requirements of the method's name (e.g. in this case, `ns_returns_retained`).

**Comment by jasperblues** [comment]
Essentially no methods are generated at run-time in Typhoon. 

- At run-time the assembly interface acts as a facade in front of an underlying TyphoonCompnentFactory, which contains blue-prints for emitting objects. Message forwarding is used here. 
- At standup assembly methods are instrumented to assign a key. Method-table swizzling is used here. While this is a valid use of swizzling, I believe I'll replace it with forwarding in the future as the same effect can be achieved, and swizzling sometimes causes controversy.

**Comment by WilliamSundqvist** [comment]
I can add that in Typhoon v. 408 "Copy" is another word which Typhoon does not like methods to start with. Same crash at populateCache.
