### ISSUE TITLE
Additional collaborating assemblies activation

### ISSUE THREAD

**Issue by igrekde** [appsquickly/Typhoon#347]
Hi!
Is it possible to activate additional assemblies on the fly?
E.g. At my Info.plist I have two assemblies: *UIAssembly* and *ServicesComponents*. Besides it, I have multiple storyboards, each one with its own assembly. I don't want to load all of them at the startup, because most of objects will be unused.
So, after *-applicationDidFinishLaunching* method, the *startUpRouter* goes into play - it should create the *TyphoonStoryboard* with the *TyphoonComponentFactory*, that includes both initial assemblies and new *UserStoryAssembly*.
Thanks for help and for the great framework!

**Comment by jasperblues** [comment]
Hi @igrekde! 

We use stackoverflow for general questions, so I've answered here: http://stackoverflow.com/a/30204022/404201

Thanks for your kinds words and for choosing Typhoon :)
