### ISSUE TITLE
Accessing the Config file in a Test Target

### ISSUE THREAD

**Issue by igrekde** [appsquickly/Typhoon#348]
Hi!
I've encountered a problem with using *TyphoonConfig* in a Test Target. When we load the config file by calling *-useResourceWithName:* method, **[NSBundle mainBundle]** is used under the hood. According to [this SO answer](http://stackoverflow.com/a/1879257), the config file cannot be found in the Test Target.
There is a workaround - I use the *-useResourceWithPath:* method, and generate the path using **[NSBundle bundleForClass:]**.
Is this the desired behavior, or should I make a PR?

**Comment by jasperblues** [comment]
I believe it needs to be this way for Swift: #329 (previously it was not). 

Perhaps the best we can do is clearly document limitations, so that the workaround is clear.

**Comment by igrekde** [comment]
And why not to replace the *-configDefinitionWithName:* with *-configDefinitionWithName:bundle:*?

**Comment by jasperblues** [comment]
That might be best actually. We can leave the old method there, but deprecate it. Or simply document that it implies the main bundle.

**Comment by igrekde** [comment]
Fine, I'll make the PR in a couple of days.

**Comment by jasperblues** [comment]
Thanks so much. When can push a micro release when ready.
