### ISSUE TITLE
Injecting an object returned by a TyphoonTypeConverter

### ISSUE THREAD

**Issue by rwbutler** [appsquickly/Typhoon#353]
I have a plist as follows defining a mapping to a custom object:

&lt;dict>
    &lt;key>myObject&lt;/key>
    &lt;string>MyObject()&lt;/string>
    &lt;key>myObject.myURL&lt;/key>
    &lt;string>NSURL(http://myurl.com )&lt;/string>
&lt;/dict>

It seems that on implementing the TyphoonTypeConverter protocol, only a concrete object can be returned from the convert method rather than another TyphoonDefinition. Is there any way to inject the custom object returned from the TyphoonTypeConverter with another property defined in the plist?

e.g. the MyObject returned by the TyphoonTypeConverter implementation would have a property myURL set to the value defined in the plist?

**Comment by jasperblues** [comment]
Yes only a custom object. When you create definitions in a `TyphoonAssembly` subclass to thing happen: 

* It is instrumented so that each definition is allocated a key. (To support code completion and refactoring without any special tool support). 
* Upon activation the definition is registered with a `TyphoonComponentFactory`. 

So if you wanted a type converter to return a `TyphoonDefinition` those steps would need to happen too.

**Comment by rwbutler** [comment]
Thanks for the info. If I drop the plist mapping and configure in the assembly e.g.

- (ViewController *)viewController {
    return [TyphoonDefinition withClass:[DataManager class] configuration:^(TyphoonDefinition *definition) {
        [definition injectProperty:@selector(dataManager) with:[self dataManager]];
    }];
}

Is there a way to inject properties into the dataManager which is already being injected into the view controller?

**Comment by jasperblues** [comment]
Yes of course. The definition for the data manager can have initializer, property or method injections. And the injections can be <a href="https://github.com/appsquickly/Typhoon/wiki/What%20can%20be%20Injected">any of these</a> - references to other definitions, scalar values (int, BOOL, etc), inline objects or something resolved from `TyphoonConfig`.

**Comment by jasperblues** [comment]
Let's continue this chat on StackOverflow! http://stackoverflow.com/questions/tagged/typhoon
