### ISSUE TITLE
iOS pre-fab definitions

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/typhoon#357]
It can be nice for code cohesion &testability to be able to injection UIWindow, current device, main screen, etc. However it is extra work to create definitions for these: 

Typhoon will let you inject an inline object: 

``` objc
[definition injectProperty:@selector(window) with:[[UIWindow alloc] init]];
```

However its not possible to define simple object (no dependencies) and register those for injection: 

``` objc
- (void)mainWindow 
{
    return [[UIWindow alloc] init];
}

[definition injectProperty:@selector(window) with:[self mainWindow]];  //Won't work!
```

Suggestions: 
- Support the 2nd case above. 
- Provide pre-fabricated definitions for iOS that can be used as a collaborating assembly. 

Which of the above is better? @JeffBNimble  ?

**Comment by itsthejb** [comment]
Definitely +1 for this. This seems to be rather hard to do, and misses out on a major selling point. Ideally, I'd like to be able to:

```
@interface InterfaceComponents : TyphoonAssembly
- (NSNotificationCenter*)notificationCenter
@end
@implentation InterfaceComponents
- (NSNotificationCenter*)notificationCenter {
	// placeholder definition
	return [TyphoonDefinition withClass:[NSNotificationCenter class]];
}
@end
```

Then I don't see how it's possible to default to injecting `[NSNotificationCenter defaultCenter]`. In particular, how about life-cycle methods so I can attach a post-processor that injects the system singleton? I can't override `-active` as this causes an infinite loop.

**Comment by itsthejb** [comment]
Some suggested pre-baked system singletons from my point of view:

* `[NSNotificationCenter defaultCenter]`
* `[NSFileManager defaultManager]`
* `[UIScreen mainScreen]`
* `[UIApplication sharedApplication]`
* `[NSLocate currentLocale]`

In fact... there are a lot! Might be nice to have Foundation and UIKit pre-baked assemblies since they are at different infrastructure "levels"

**Comment by jasperblues** [comment]
@itsthejb  Which do you like better? 

* Ability to define a method that returns a 'simple' (ie non-definition) object and have it participate in the assembly. 
* Pre-fab definitions

Both? 

I like the former, except that it introduces another concept that people will need to learn. At the moment, along with short-comings we have consistency.

**Comment by itsthejb** [comment]
I certainly like the former, although it does look out of place amongst other "normal" definitions. I imagine it might be more consistent, and easier to implement, to have something like:

`+[TyphoonDefinition withObject:(id)object]`

To me this is clearer, and no sweat for a user who has learnt to use the "full" definitions patterns.

As for the actual pre-fab concept, do you mean hard-coding these singletons into the library? Certainly there are some obvious ones that people will want, but they should certainly be implemented with a nice pattern that doesn't require first-party support.

**Comment by jasperblues** [comment]
That's a nice idea. Thanks. 

Yes, I meant an optional UIKitAssembly and FoundationAssembly that can be used as collaborating assemblies.

**Comment by itsthejb** [comment]
Sounds good! I thought another slight adaptation of the suggestion would be:

```
	return
	[TyphoonDefinition withClass:[NSNotificationCenter class]
				   configuration:^(TyphoonDefinition *definition)
	 {
		 [definition injectValue:[NSNotificationCenter defaultCenter]];
	 }];
}
```

This is even closer to the usual pattern

**Comment by plandem** [comment]
E.g.: i have themeAssembly, it worked well, till i wanted to add a method that will return just play NSArray with list of theme:
```
-(NSArray *)themeList;
```

I just need array, no definition. But i would like to put it on themeAssembly, because for other cases that assembly is working fine. Looks like right now i have to create such "wrapper":
```
-(NSArray *)themeList {
	return [TyphoonDefinition withClass:[NSArray class] configuration:^(TyphoonDefinition *definition) {
		[definition useInitializer:@selector(arrayByAddingObjectsFromArray:) parameters:^(TyphoonMethod *initializer) {
			[initializer injectParameterWith:@[
					@"default.json",
					@"pink.json",
			]];
		}];
	}];
}
```

that's looks a bit weird and as main purpose factory(decrease boilerplate code) - doesnot help.

**Comment by itsthejb** [comment]
Any movement on this? Just hitting another case where I'd want this (`NSUserDefaults`), and it sucks pretty hard that it's not even possible to do this :cry:

**Comment by jasperblues** [comment]
Yes @alexgarbarev added a useful feature the other day. 

You can now do: 

```objc

//Replace this with whatever defaults you want at any time. 
- (NSUserDefaults*)defaults {
    return [TyphoonDefinition withObject:[NSUserDefaults sharedUserDefaults]];
}

**Comment by itsthejb** [comment]
Great! I'll check this out right now...

**Comment by jasperblues** [comment]
@itsthejb Thanks for the remind that this needs to be added to the user guide.

**Comment by alexgarbarev** [comment]
I believe it's
```
- (NSUserDefaults*)defaults {
    return [TyphoonDefinition with:[NSUserDefaults sharedUserDefaults]];
}
```
