### ISSUE TITLE
Can we use CFBundleExecutable instead of CFBundleName?

### ISSUE THREAD

**Issue by VincentWenShuo** [appsquickly/Typhoon#359]
We encounter a problem with changing app name when we are using Typhoon framework.

The problem is in TyphoonIntrospectionUtils.m, for function "Class TyphoonClassFromString(NSString *className)"

NSString *defaultModuleName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];

So if we change the BundleName in Info.plist to a different name from the project name, the Typhoon won't work any more. 

Can we use CFBundleExecutable or something else instead? So that we can easily change our app name.

Thanks a lot.

**Comment by jasperblues** [comment]
That was for swift name-spacing. Does it work with CFBundleExecutable?

**Comment by VincentWenShuo** [comment]
Yes, we tried and it worked. But we are using pod for our CI, so it is
better you guys can modify this.

Thanks

**Comment by jasperblues** [comment]
Ok. Please paste the update method from `TyphoonIntrospectionUtils` here.

**Comment by VincentWenShuo** [comment]
Just change

NSString *defaultModuleName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];

to

NSString *defaultModuleName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleExecutable"];

**Comment by jasperblues** [comment]
Done. You can now try this with: 

```ruby
pod 'Typhoon', :head
```

**Comment by VincentWenShuo** [comment]
It is working now. thanks.

**Comment by jasperblues** [comment]
Thank you :)
