### ISSUE TITLE
Using OCMock objects (or other lightweight proxy) not working with runtime args

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#363]
@itsthejb reports that mock objects (or other proxies, probably) don't work with runtime args system.

**Comment by alexgarbarev** [comment]
@jasperblues any examples?

**Comment by igrekde** [comment]
I've made a couple of unit tests trying to reproduce this issue (PR #377). Unfortunately, I can't see any exception.

**Comment by jasperblues** [comment]
@itsthejb Are you able to give us some more details. A sample project?

**Comment by itsthejb** [comment]
Actually can't reproduce on a blank project now, and the case where I noticed this in our main project was a long time and not possible to share... It may be a non-issue, hard to remember exactly what happened.

**Comment by jasperblues** [comment]
@itsthejb  Closing for now. Let us know if you encounter it again.

**Comment by itsthejb** [comment]
Ok!
