### ISSUE TITLE
Assembly convenience accessors

### ISSUE THREAD

**Issue by itsthejb** [appsquickly/Typhoon#364]
Hi there,

Suppose I have the following assembly:

```
@interface DeviceServices : TyphoonAssembly
@end

@implementation EYEDeviceServices
- (id)userInterfaceIdiomValue {
	return [TyphoonDefinition withClass:[NSNumber class] configuration:^(TyphoonDefinition *definition) {
		return [definition useInitializer:@selector(initWithInteger:) parameters:^(TyphoonMethod *initializer) {
			[initializer injectParameterWith:@([UIDevice currentDevice].userInterfaceIdiom)];
		}];
	}];
}
@end
```

I'd really like to be able to access an injecting `UIUserInterfaceIdiom` value directly rather than having to unbox every time. However, adding a convenience accessor:

```
@interface DeviceServices : TyphoonAssembly
@property (readonly) UIUserInterfaceIdiom userInterfaceIdiom;
@end

@implementation EYEDeviceServices
- (UIUserInterfaceIdiom)userInterfaceIdiom {
    return [self.userInterfaceIdiomValue integerValue];
}
@end
```

Doesn't work since the factory will go looking for a key for `userInterfaceIdiom`. Is there any way to achieve this right now? If not, it would be a great feature. I notice that the definition builder already ignores properties, so it seems like readonly property support should *almost* work. It's only when the value is accessed that you get an exception. Also, `TyphoonTypeConverter` doesn't *appear* to support this since I want a primitive?

Thanks!

**Comment by jasperblues** [comment]
There's talk about ( #357 , and elsewhere) ability to define a shared object (not a definition) to inject in several places. Eg: 

```objc
- (UIWindow *)window 
{
    return [[UIWindow alloc] init];
}
``` 

The above currently doesn't work for a few fairly trivial reasons. An extension of that would be the ability to return a primitive, like an enum, and for Typhoon to detect this and automatically wrap it, as is required when injecting primitives. 

WRT TyphoonTypeConverter, there's a special TyphoonTypeConverter for primitives types - `TyphoonPrimitiveTypeConverter` - and it could probably be used as the basis of an enum type converter.

**Comment by itsthejb** [comment]
Sounds good. This is no blocker for us, but would be great in the long run to be able to use injected values without the one extra unboxing line

**Comment by igrekde** [comment]
Seems to be already implemented in Issue #357.

**Comment by itsthejb** [comment]
Indeed. #357 lets this be done "properly" by injecting the shared instances themselves. Much superior pattern, and an excellent new feature

**Comment by jasperblues** [comment]
:+1: We could've allowed them to be declared inline, but we thought wrapping them in TyphoonDefinition would provide overall consistency, and no new concepts to learn.

**Comment by itsthejb** [comment]
For sure. Very happy with the implementation
