### ISSUE TITLE
fix documentation

### ISSUE THREAD

**Issue by plandem** [appsquickly/Typhoon#366]
at https://github.com/appsquickly/Typhoon/wiki/What-can-be-Injected, there is examples for configs.

json example is not same as properties or plist - you will not be able to get 'service.url' for such json config. Valid key - 'config.service.url'. I would suggest to fix it to make configs similar.

**Comment by jasperblues** [comment]
Thanks for reporting.

**Comment by igrekde** [comment]
Fixed - thanks for suggestions!
