### ISSUE TITLE
TyphoonFactoryDefinition.h is not visible by default

### ISSUE THREAD

**Issue by plandem** [appsquickly/Typhoon#370]
i'm not sure that it's a issue(don't know possible reason not to do it), but by default TyphoonFactoryDefinition is not visible if i import only 'Typhoon.h'

**Comment by jasperblues** [comment]
Seems the class was missing from the umbrella header. To test (with CocoaPods) 

```ruby
pod 'Typhoon', :head
```

**Comment by alexgarbarev** [comment]
By default, `TyphoonFactoryDefinition` was hidden, becuase it's internal symbol. It's not for users. It's created automatically by class cluster method ```withFactory:``` of `TyphoonDefinition`

**Comment by alexgarbarev** [comment]
Why we need that header in umbrella header? I would like to revert that..

**Comment by plandem** [comment]
Because if you will try to create a definition withFactory and configure it you will get 'forward declaration'.

+ (id)withFactory:(id)factory selector:(SEL)selector parameters:(void (^)(TyphoonMethod *))parametersBlock
    configuration:(void (^)(TyphoonFactoryDefinition *))configuration
{

}

**Comment by alexgarbarev** [comment]
Ah... That's right.
