### ISSUE TITLE
static library

### ISSUE THREAD

**Issue by OborinPavel** [appsquickly/Typhoon#375]
Can I build a Typhoon as a static library?
I cannot use cocoaPods as I cannot force a customer to use them. On other side I cannot use a dynamic framework as I need to support an iOS7 for the time being.

**Comment by jasperblues** [comment]
Hi! Yes you can, no problem. 

Either drag the source files into your project, and create a static library target for that, then add as a dependency to another target, or checkout Typhoon and build from there.

**Comment by OborinPavel** [comment]
I thought the project has it.

Cheers.

**Comment by jasperblues** [comment]
We're looking at reconfiguring our build server, and uploading latest binaries as part of that, hence issue reopened. (In the meantime you'll still have to build manually).

**Comment by OborinPavel** [comment]
That's a great news! Looking forward to get binaries

**Comment by jasperblues** [comment]
Closed by #478
