### ISSUE TITLE
Activated assembly returns a TyphoonDefinition object in swift 2.0

### ISSUE THREAD

**Issue by soniccat** [appsquickly/Typhoon#385]
Using Xcode Beta 3 (7A152u) I see that having Assembly subclasses in objc and swift files gives different results. In the objc assembly subclass the forwardInvocation method is called and I get an expected object. In swift it isn't called and I get an object of TyphoonDefinition class.

```
        assembly = CoolAssembly().activate()
        assembly2 = OldAssembly().activate()

        let me = assembly.entity()
        let me2 = assembly2.movable()
```

swift version

```
@objc class CoolAssembly: TyphoonAssembly {
    @objc func entity() -> AnyObject {
        return TyphoonDefinition.withClass(Castle.self, configuration: { (def:TyphoonDefinition!) -> Void in
        })
    }
}
```

objc version

```
@implementation OldAssembly

- (id)movable {
    return [TyphoonDefinition withClass:[Bed class] configuration:^(TyphoonDefinition *definition) {
    }];
}

@end
```

**Comment by jasperblues** [comment]
Hello @soniccat, thanks for reporting - somehow we didn't see this until now. 

Behavior is not good! Will try to find a workaround.

**Comment by iSevenDays** [comment]
Is there any solution?

**Comment by etolstoy** [comment]
We strongly recommend to use the [pure Swift version](https://github.com/appsquickly/TyphoonSwift) of Typhoon.
