### ISSUE TITLE
3.2.2 not building framework

### ISSUE THREAD

**Issue by akiraspeirs** [appsquickly/Typhoon#387]
Hi, I'm new to Typhoon. I tried to set it up using Carthage got a build error.
I had a look at Typhoon.xcodeproj/xcshareddata/xcschemes/Typhoon.xcscheme and it was set to build an app rather than a framework. I got it working perfectly when I changed it to build a framework.
Looks like it was accidentally changed in b00dd8161eb2ebb34a325be08cb69111075d0215?

I'm actually new to Github too, was wondering if I should be making pull requests for something like this?

Really excited to start using Typhoon :)

**Comment by jasperblues** [comment]
Hello @akiraspeirs 

Yes please we'd love a pull request for this. Users started reporting this problem a few days ago, and I wasn't sure what went wrong.

**Comment by jasperblues** [comment]
It looks like users are still having problems: http://stackoverflow.com/a/31635659/404201

**Comment by akiraspeirs** [comment]
It looks like there's a different issue causing this problem introduced in 3.1.9.

TyphoonFactoryDefinition.h was included in the umbrella header in aa6f8e6da264e35a0965d39a00add474610e61e9, but it's not included in the public headers in the target's Headers build phase.

I could fix the problem by either:
- removing TyphoonFactoryDefinition.h from the umbrella header; or 
- adding it to the exported public headers.

The file is in an internal directory, so maybe it shouldn't be included? Or was it added for a good reason?

**Comment by jasperblues** [comment]
I believe its supposed act like a class cluster so that any methods that return an instance of `TyphoonFactoryDefinition` will be defined on the ordinary base class (`TyphoonDefinition`). Checking if that's still the case. If not, we should move it out of the internal folder.

**Comment by jasperblues** [comment]
Hmmm. Since users are effected by this problem and waiting for a solution, let's just add to the exported headers. That seems like the fastest way to get things working again.

**Comment by jasperblues** [comment]
Closing - I believe this has been fixed.
