### ISSUE TITLE
OCLogTemplate.h file is not found

### ISSUE THREAD

**Issue by ytx0574** [appsquickly/Typhoon#391]
I download the zip package, no 'OCLogTemplate.h' the file, whether to submit code has been omitted

**Comment by jasperblues** [comment]
Hello @ytx0574 

OCLogTemplate is available here: https://github.com/appsquickly/OCLogTemplate

* If you do a git clone of Typhoon, then its set up as a sub-module. (Use `git submodule init` & update). 
* If you install via CocoaPods then this is handled as a dependency. 
* If you install via Carthage it is similarly handled as a dependency.

**Comment by ytx0574** [comment]
I am directly open the downloaded zip package, there is no found OCLogTemplate.h, I use the CocoaPods, behind with this file. I'm sorry, I didn't see the document, thank you very much for your answer

**Comment by jasperblues** [comment]
@ytx0574  You're welcome. We're always happy to answer questions.
