### ISSUE TITLE
sub assembly can't be accessed via plist integration in swift

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#392]
http://stackoverflow.com/questions/31684272/accessing-sub-assembly-of-an-assembly-will-generate-exc-bad-access

**Comment by fatuhoku** [comment]
Is this related to #418?  I want assemblies injected via protocols, which is sort of a collaborating, 'subassembly'

**Comment by kamil3** [comment]
What is the progress of this issue?

**Comment by etolstoy** [comment]
The issue has a solution by @jasperblues. However, we strongly recommend to use the [pure Swift version](https://github.com/appsquickly/TyphoonSwift) of Typhoon.
