### ISSUE TITLE
Are there plans for Typhoon to support Objective-C or swift generics?

### ISSUE THREAD

**Issue by jshin47** [appsquickly/Typhoon#393]
It looks like the next major release of Obj-C will have generics, and swift does already.

In my experience, `Typhoon` will not tolerate duplicate definitions in the sense that if `ConcreteA` conforms to `Protocol1`, a single assembly cannot have methods that return both without parameters.

Unless `Typhoon` is already generics-aware, I would imagine that `ConcreteA<T1>` and `ConcreteA<T2>` look the same to `Typhoon`.

**Comment by jasperblues** [comment]
Although Objective-C's loose type system means that its technically not necessary to cast, the other benefits of generics are realized: 

* Type checking at compile time. 
* Documentation

. . . so we're pretty happy about this new feature. Having said that, I haven't looked into it much yet. We want Typhoon to generally be backwards compatible, so whatever we do provide will need to meet that requirement. 

We have, however, started R&D on the 'pure swift' version of Typhoon.

**Comment by jasperblues** [comment]
Closing this. Let's proceed by opening defined issues for features associated with generics.
