### ISSUE TITLE
Is it possible to use SWRevealViewController + Storyboard + Typhoon?

### ISSUE THREAD

**Issue by thefenix1** [appsquickly/Typhoon#396]
I'm trying to inject view controllers using typhoon. I was quite happy with the idea of start using this component but I faced a roadblock: since I'm using SWRevealViewController, this component is taking care of creating front and rear view controllers. Because of this, I can't inject properties to them since creation process is out of my hands.

Is there any workaround to inject dependencies while using SWRevealViewController?

Thanks

**Comment by alexgarbarev** [comment]
How SWRevealViewController creates ViewControllers? How it understand classes for these viewControllers? Is there customization point of controllers creation?

**Comment by thefenix1** [comment]
Not sure if you know the library, but everything is done on storyboard, there is no code involved. You define some custom segues to specify which controller is front and which one is menu. I'm not aware of any customization point when using storyboard but definitively I could be missing something.

I was hoping that someone was more familiar than me connecting these components. Not sure how documented it is SWRevealViewController but they have examples on repo explaining how it works.

Thanks

**Comment by mogol** [comment]
@thefenix1 ,
I guess, you could use 2 variants.
First, try to create SWRevealViewController from typhoon assembly, using initializer ```-initWithRearViewController:frontViewController:```
Second, use property injection for TyphoonStoryboard by using 
```objectivec
@property (nonatomic) UIViewController *rearViewController;
@property (nonatomic) UIViewController *rightViewController;
@property (nonatomic) UIViewController *frontViewController;
```

**Comment by thefenix1** [comment]
I'll try it and let you know how it goes. Thanks, you're great!

**Comment by thefenix1** [comment]
This worked great, thanks! I lost navigation controller from view using this "manual" approach though (navigation bar doesn't show up). I'll see what's wrong with that.

**Comment by alexgarbarev** [comment]
@thefenix1 If your back and front viewController made from Main storyboard, then all dependencies must be injected automatically by Typhoon. If they doesn't - that's a bug. (Small demo projects would be nice to debug)

**Comment by thefenix1** [comment]
I've created a small sample recreating my problem. You can download it from here https://www.dropbox.com/s/ihk4tkvgcaghgvg/TestTyphoon.zip?dl=0

If you check "ViewControlller" class, you'll see that there is a presenter property that I inject on "MainAssembly".

This code represents my original approach and not @mogol suggestion and I understand from you that it should work. 

My feeling is that it's not a bug but a problem with how SWRevealViewController do his stuff, but I'd love to hear from you.

You're more thank great man :)

**Comment by alexgarbarev** [comment]
Hey @thefenix1,

Thanks for demo project.

Just checked your code. The problem not in SWRevealViewController, because all viewControllers creation done by storyboard.

Problem in that code:

```
    dynamic func viewController() -> AnyObject {
        return TyphoonDefinition.withFactory(self.applicationAssembly.mainStoryboard(), selector: "instantiateViewControllerWithIdentifier:", parameters: {
            (factoryMethod) in
            
            factoryMethod.injectParameterWith("ViewController")
        }, configuration: {
            (definition) in
            definition.injectProperty("presenter", with: self.presenter())
            definition.injectProperty("rootWireframe", with: self.applicationAssembly.rootWireframe())
        })
    }
```

There is no chance for Typhoon to understand - what is kind of instance (class) returned by this method. You using **factory method** here, so in theory it can be object of any class. You should tell Typhoon that _this definition produce objects of class `ViewController`_.
This is how to that:
```
    dynamic func viewController() -> AnyObject {
        return TyphoonDefinition.withFactory(self.applicationAssembly.mainStoryboard(), selector: "instantiateViewControllerWithIdentifier:", parameters: {
            (factoryMethod) in
            
            factoryMethod.injectParameterWith("ViewController")
        }, configuration: {
            (definition) in
            definition.injectProperty("presenter", with: self.presenter())
            definition.injectProperty("rootWireframe", with: self.applicationAssembly.rootWireframe())
            definition.classOrProtocolForAutoInjection = ViewController.self // <-- this line
        })
    }
```

Alternatively, if your `ViewController` only created by storyboard, you can simplify your definition to that:
```
    dynamic func viewController() -> AnyObject {
        return TyphoonDefinition.withClass(ViewController.self) {
            (definition) in
            definition.injectProperty("presenter", with: self.presenter())
            definition.injectProperty("rootWireframe", with: self.applicationAssembly.rootWireframe())
        }
    }
```
In that case you can't create your `ViewController` using that assembly method, but `TyphoonStoryboard` will catch that and understand which dependencies to inject into `ViewController`

**Comment by thefenix1** [comment]
That works! I can't express how much I appreciate your help with this. I'm 100% new to Typhoon and quite new to iOS development in general.

Thanks :)
