### ISSUE TITLE
Is it possible to inject using "useInitializer" when method includes swift pure protocols?

### ISSUE THREAD

**Issue by claudioredi** [appsquickly/Typhoon#400]
I have the following initializer

<pre> init(database: DatabaseProtocol, deserializerFactory: DeserializerFactory ) {
        self.database = database
        self.deserializerFactory = deserializerFactory
}</pre>

and I try to inject parameters using 

<pre>definition.useInitializer("initWithDatabase:deserializerFactory:") {
         (initializer) in
                
         initializer.injectParameterWith(self.dataStoreAssembly.database())
         initializer.injectParameterWith(self.dataStoreAssembly.deserializerFactory())
}</pre>

So far I understand, I should add `@objc` to `DatabaseProtocol`. Problem is that I can't do this since it has members that can't be represented in objective c

**Comment by jasperblues** [comment]
Hello @claudioredi !

You can declare your initializer as: 

```swift
 dynamic init(database: DatabaseProtocol, deserializerFactory: DeserializerFactory ) {
        self.database = database
        self.deserializerFactory = deserializerFactory
}
```

Also please ask these kinds of questions on StackOverflow's Typhoon channel - its very well indexed by Google and so helps other users in future.
