### ISSUE TITLE
Is TyphoonComponentFactoryAware still a thing?

### ISSUE THREAD

**Issue by epologee** [appsquickly/Typhoon#402]
[TyphoonComponentFactory.h:136 (on `master` as of august 2015)](https://github.com/appsquickly/Typhoon/blob/00f3a4014710fc9362c0ee18c9bee2c0e8a232e8/Source/Factory/TyphoonComponentFactory.h#L136) mentions a protocol called `TyphoonComponentFactoryAware`. It's also mentioned in the changelog, but unless this is a dynamically composed protocol name, it seems to be missing from the rest of the codebase.

Is `TyphoonComponentFactoryAware` still a thing? And if not, what would be the current preferred way of getting properties correctly injected?

**Comment by jasperblues** [comment]
@epologee These methods were renamed in Typhoon 2.0. Sorry for the confusion. You can now add the following to any typhoon created/injected instance: 

```objc
- (void)typhoonWillInject 
{
}

- (void)typhoonDidInject
{
}
```

You can also specify a custom callback method on a definition: 

```objc
[definition peformAfterInjections:@selector(SomeMethod) withArguments . . . ]
```

Use the former for convenience, and the latter if you do not wish to couple your class to Typhoon.

**Comment by epologee** [comment]
Thanks!
