### ISSUE TITLE
Designated initializer should only invoke a designated initializer on 'super'

### ISSUE THREAD

**Issue by digitwolf** [appsquickly/Typhoon#405]
Hi,

When I am running unit tests on Typhoon **v3.2.8** with XCode7, I get this error:
TyphoonDefinition+Infrastructure.m:88:18: 
**Designated initializer should only invoke a designated initializer on 'super'**

<img width="856" alt="screen shot 2015-09-01 at 5 25 40 pm" src="https://cloud.githubusercontent.com/assets/1285978/9620389/8703f9f2-50ce-11e5-8ac0-04a343e76f5b.png">

Is this an XCode7 related issue?

**Comment by mogol** [comment]
Hey @digitwolf ,
I have same problem with XCode7 beta6. 
but we should wait release version. 
 
You could move initWithClass:Key: from category to class implementation, then it will be correct.

**Comment by digitwolf** [comment]
Thank you, @mogol 
I was wondering, if I should create a pull request for this?

**Comment by mogol** [comment]
@digitwolf , PR will be great!
But let's wait for release of Xcode.

**Comment by NielsKoole** [comment]
I have this same issue and because of that I cannot validate my own Cocoapod. Is there something to fix this?
