### ISSUE TITLE
Collaborating Typhoon assemblies results in “Can't find assembly of type” info log message

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#408]
http://stackoverflow.com/q/32407554/404201

**Comment by jasperblues** [comment]
Seems not fixed? http://stackoverflow.com/a/32407909/404201

**Comment by igrekde** [comment]
@jasperblues I build a new project from scratch with the same setup as described on stackoverflow. The issue is reproducing with the version 3.2.8, but with 3.3.3 it's fine - no warnings, the assembly is injected fine.

**Comment by jasperblues** [comment]
@igrekde Thanks for the update - will pass that on to OP on StackOverflow. Probably user error, but if still not resolved will ask for sample project.

**Comment by igrekde** [comment]
By the way, I've reproduced this issue in one of our work projects - and fixed the problem by updating to version 3.3.3

**Comment by mthole** [comment]
Confirmed: v3.3.3 fixed this for me as well.  I originally reported this in StackOverflow, but must've done something silly on my end to not *actually* deploy the 3.3.3 update. Suggest we close this issue, thanks!

**Comment by jasperblues** [comment]
thanks for the confirmations/reminders @igrekde @mthole
