### ISSUE TITLE
TyphoonAssembly.defaultAssembly throws cast exception in Swift

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#409]
http://stackoverflow.com/questions/32426214/typhoon-defaultassembly-in-swift/32429303#32429303

**Comment by etolstoy** [comment]
The issue has a solution by @jasperblues. However, we strongly recommend to use the [pure Swift version](https://github.com/appsquickly/TyphoonSwift) of Typhoon.
