### ISSUE TITLE
how to return 'nil' in 'TyphoonAssembly'?

### ISSUE THREAD

**Issue by belkevich** [appsquickly/Typhoon#410]
Hi!
I want to stub `analytics` property with `nil` in test target. But I stuck with `No component matching id` exception. 
Here is an assembly code:
```objective-c
- (NSObject <AnalyticsProtocol> *)analytics {
    return nil;
}
```

**Comment by alexgarbarev** [comment]
How do you inject your property in assembly? What is condition to return nil (how do you understand that you on test target in code? Separate assembly?)

**Comment by jasperblues** [comment]
Assuming you are following Typhoon's guidelines for integration testing here: https://github.com/appsquickly/Typhoon/wiki/Integration-Testing

Then you can either: 

- Path out a class for another: https://github.com/appsquickly/Typhoon/wiki/Integration-Testing#patching-out-a-component

- Use override an assembly with another: https://github.com/appsquickly/Typhoon/wiki/Integration-Testing#patching-out-a-component

I can't think of a good way to return nil, but using either of the two techniques above you could return: 

- A mock object in place of `<AnalyticsProtocol>` . . using a so-called 'easy' mock frame work like OCMockito means you don't have to record expectations in advance. The mock accepts all messages (like nil does)
- Put a stub in place of the real analytic service. 

Obligatory: http://martinfowler.com/articles/mocksArentStubs.html

**Comment by belkevich** [comment]
> How do you inject your property in assembly?
I have `UIAssembly`, that build some `ViewController` with property `analytics`. Value of `analytics` should be build by `BusinessLogicAssembly`. `UIAssembly` owns `BusinessLogicAssmebly` by `BusinessLogicAssemblyProtocol`. 

> What is condition to return nil (how do you understand that you on test target in code? Separate assembly?)
Yes. I have 2 implementation of `BusinessLogicAssemblyProtocol`. One for app and one for test.

P.S. Thank you for fast feedback

**Comment by alexgarbarev** [comment]
@jasperblues I think that another could be:

```
#define TESTS 1

- (NSObject<AnalyticsProtocol>*)analytics {
    return [TyphoonDefinition withOption:@(TESTS) yes:[self realAnalyticsDefinition] no:nil];
}
```

But actually I think we should add something like:
```
- (NSObject<AnalyticsProtocol>*)analytics {
    return [TyphoonDefinition nil];
}
```

**Comment by belkevich** [comment]
```
- (NSObject<AnalyticsProtocol>*)analytics {
    return [TyphoonDefinition nil];
}
```

Unfortunately this code doesn't build. 
Also I can't return `NSNumber *` value in any method of `TyphoonAssembly` subclass.
Am I right, every method of `TyphoonAssembly` subclass should return `TyphoonDefinition`?

**Comment by jasperblues** [comment]
Or come to think of it, with `TyphoonPatcher` you don't have to return a mock or a stub. If you really want nil you could just: 

```objc
TyphoonPatcher* patcher = [[TyphoonPatcher alloc] init];
[patcher patchDefinitionWithSelector:@selector(analytics) withObject:^id{
   return nil;
}];
```

@belkevich Sorry for the confusion. Aleksey was suggesting a possible future feature there. His first example works with current Typhoon, second example is a proposed feature.

**Comment by belkevich** [comment]
@jasperblues 
Could you provide example where I should add `patcher` in my case?

**Comment by belkevich** [comment]
Also it would be great to have features like this:
```objective-c
- (NSObject <Analytics> *)analytics {
    return [TyphoonDefinition withNil];
}

- (NSNumber *)userID {
    return [TyphoonDefinition withValue:@(12345)];
}

**Comment by jasperblues** [comment]
@belkevich  sure, can you show me your test class (or just the part where you instantiate Typhoon) and il'll edit for you. 

Yes I agree with @akiraspeirs and yourself that those are useful. In the past we also propsed just mixing in: 

```
- (id)analyticsService
{
    //return any object or nil
}
```

And have Typhoon detect that this is 'not a definition', therefore treat as object. . But we were worried that: 

- might add complexity and learning curve.

**Comment by alexgarbarev** [comment]
These features on the way now :-)

**Comment by alexgarbarev** [comment]
Hey @jasperblues , @belkevich. Good news here.
New method is available:
```
[TyphoonDefinition with:anything];
```

Example of usages (grabbed from our unit tests):
```
- (id)nullQuest
{
    return [TyphoonDefinition with:nil];
}

- (id)knightWithNullQuest
{
    return [TyphoonDefinition withClass:[Knight class] configuration:^(TyphoonDefinition *definition) {
        [definition injectProperty:@selector(quest) with:[self nullQuest]];
    }];
}

- (NSNumber *)simpleNumber
{
    return [TyphoonDefinition with:@(1)];
}

- (NSString *)simpleString
{
    return [TyphoonDefinition with:@"123"];
}

- (NSString *(^)())blockDefinition
{
    return [TyphoonDefinition with:^NSString *(){
        return @"321";
    }];
}

- (NSString *)referenceToSimpleString
{
    return [TyphoonDefinition with:[self simpleString]];
}

- (NSArray *)simpleArray
{
    return [TyphoonDefinition with:@[[self simpleString], [self referenceToSimpleString], @"123"]];
}

- (id)simpleRuntimeArgument:(id)argument
{
    return [TyphoonDefinition with:argument];
}
```

**Comment by igrekde** [comment]
@alexgarbarev Looks great, thanks! 👍

**Comment by belkevich** [comment]
Wow! Looks great!
Is it available on cocoapods?

**Comment by alexgarbarev** [comment]
@belkevich yes. Version ``3.3.0``

**Comment by belkevich** [comment]
Thank you! I'll check it and close the issue.

**Comment by jasperblues** [comment]
@alexgarbarev great work

@belkevich  no need to close the issue, for new features we do code reviews first - it helps shared ownership, information sharing, etc.
