### ISSUE TITLE
Typhoon.framework target needs to be included in CI build

### ISSUE THREAD

**Issue by peterkutasi** [appsquickly/Typhoon#411]
Hi,

It seems the framework target is broken in the latest (3.3.0) version. I've tried to use it with Carthage and it turned out the `TyphoonInjectionDefinition` class is missing from the framework target.

**Comment by peterkutasi** [comment]
I made this PR which should fix it: https://github.com/appsquickly/Typhoon/pull/412

**Comment by jasperblues** [comment]
Thanks again @peterkutasi  - PR merged and tagged as 3.3.1. Also pushed to CccoaPods mater repo. 

Leaving this open until the CI build tests that target. Will fix ASAP. Sorry for the inconvenience.

**Comment by peterkutasi** [comment]
np, it's my pleasure :)
