### ISSUE TITLE
Umbrella header for module 'Typhoon' does not include header 'TyphoonSwizzler.h'

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#413]
Building a my project with Xcode 6.4, Typhoon 3.3.0, using Cocoapods to include Typhoon.

**Comment by igrekde** [comment]
Hi, @fatuhoku . Thanks for reporting a lot of new issues! 👍

As far as I know, the `TyphoonMethodSwizzler` is not intended to be public - it's just a helper class for our internal needs, so it shouldn't be included in the umbrella header.

On the other hand, it's rather universal and independent, so, if you really want to use it manually, I think we can extract it for the public use.

What do you think?

**Comment by fatuhoku** [comment]
Hi @igrekde — I actually didn't intend to be using the class at all. Actually I just got this warning seemingly out of nowhere when building the project. I haven't seen this warning since I wrote the issue so I cannot give you exact reproduction steps. Happy to have this closed until I see it again!
