### ISSUE TITLE
Built-in support for storyboard references

### ISSUE THREAD

**Issue by igrekde** [appsquickly/Typhoon#415]
Currently *Typhoon* injects the `TyphoonComponentFactory` only in the main storyboard of the application - and you need to instantiate other storyboards manually using the `-storyboardWithName:bundle:factory:` method.

With Xcode 7 we have the brand new feature of creating [storyboard references](https://developer.apple.com/library/prerelease/ios/recipes/xcode_help-IB_storyboard/Chapters/AddSBReference.html), so it'd be very convinient to implement automated instrumenting of all the storyboards in the application.

**Comment by alexgarbarev** [comment]
Looks nice. So it would works only if parent storyboard is TyphoonStoryboard too, right? Looks like easy to implement :-)

**Comment by igrekde** [comment]
@alexgarbarev,

**Comment by igrekde** [comment]
@alexgarbarev Well, I don't see a nice way to determine the parent storyboard. I've thought of using `TyphoonInitialStoryboardResolver` for all the storyboards in the application bundle, except the ones blacklisted in the Info.plist file.

**Comment by igrekde** [comment]
Implemented in v.3.3.4
