### ISSUE TITLE
definition.useInitializer("...") with Swift protocols as parameters forces @obj annotation in Swift

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#417]
Let's say I have a Swift class that declares the following initializer:

```swift
class SomeClass {
    init(dataStore: SomeDataStore, presenter: SomePresenter) {
        self.dataStore = dataStore
        self.presenter = presenter
        super.init()
    }
}
```

When I declare a component of type `SomeClass`, I tell Typhoon to use that initializer by saying `definition.useInitializer("initWithDataStore:presenter:")`.  But when I do this I get `failed: caught "NSInvalidArgumentException", "Method 'initWithDataStore:presenter:' not found on 'SomeClass'. Did you include the required ':' characters to signify arguments?"`.

I figured you probably need to annotate the initializer thus for the Objective-C method name to be found:

```swift
    @objc(initWithDataStore:presenter:)
    init(dataStore: SomeDataStore, presenter: SomePresenter) {
        // ... same as before...
    }
```

... but then this cascades and forces `SomeDataStore`, `SomePresenter` (they're protocols) to all be annotated with `@objc`.  i.e. These become Objective-C class-only protocols rather than supporting structs & enums as well.

Is there a Swift-only way of using Typhoon that lets me specify which class initializer to use WITHOUT making me cascade `@objc` annotations for all types involved?

I do **not** wish to use setter injection if it can be helped.

**Comment by fatuhoku** [comment]
#257 Just found out that you have to use `@objc` protocols if you want to use `useInitializer`. This is a not a great solution, because this forces all of your `@protocol`'s methods to be `@objc` as well.

Is this officially a limitation of Typhoon?

**Comment by fatuhoku** [comment]
I've done a bit of digging. With tools like the ones outlined here: https://netguru.co/blog/reflection-swift  is Typhoon planning to take advantage of Swift's read-only reflection?

**Comment by jasperblues** [comment]
No, unfortunately this kind of reflection is not useful for Typhoon. It is good for supporting eg InterfaceBuilder and Storyboards.

**Comment by jasperblues** [comment]
@fatuhoku closing this: There's really no way to avoid the problem, unless we wrote a "pure swift"  injector that does not use reflection or the objc runtime.

**Comment by fatuhoku** [comment]
:/

@jasperblues thanks for the note.  This really hampers that 'dependency resolution' of Typhoon... when everything has to be explicitly injected it feels like Typhoon becomes a glorified enterprise-scale `init` tool. Sad!

**Comment by jasperblues** [comment]
@fatuhoku Yeah. . . without reflection or method interception in Swift I think the answer lies in other approaches. 

* We could go for a light-weight style DI container that uses closures
* Or, in the spirit of ARC vs garbage collection we could shift from runtime to compile time tooling. 

. . . but building more on top of a non-ideal foundation is not the answer. Typhoon+Swift is already stetching it a bit in terms of what is acceptable. Anything we built on the current foundation would just add more annoying constraints and quirks.
