### ISSUE TITLE
There's no way to inject a collaborating assembly by protocol type in Swift (TyphoonAssembly <Protocol> Syntax doesn't exist in Swift)

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#418]
I'm using Typhoon to test an assembly called `FooAssembly`, which requires a collaborating sort of assembly `BarAssembly`. I have a test instantiation of `BarAssembly`, known as `TestBarAssembly`. Here's how it looks:

``` swift
protocol BarAssembly {
    func barComponent() -> AnyObject 
}

class FooAssembly : TyphoonAssembly {
    var barAssembly: BarAssembly!
    func fooComponent() {
        return TyphoonDefinition.withClass(FooComponent.self) {
            (definition) in
            definition.useInitializer("initWithBar:") {
                 (initializer) in
                 initializer.injectParameterWith(self.barAssembly.barComponent())
            }
        }
    }
}

class TestBarAssembly : TyphoonAssembly, BarAssembly {
    func barComponent() {
        // define a fake barComponent.
    }
}
```

In my CocoaTouch test target, I do not use plist integration. Instead, on the top of a test file, I do:

``` swift
private let assembly = FooAssembly().activateWithCollaboratingAssemblies([
    TestBarAssembly()
])
```

Perfectly reasonable. But then when I go:

``` swift
// ...
it("blah blah") {
    let bar = assembly.fooComponent()
}
```

... it fails, saying that `barAssembly` is `nil`.  Having explicitly told Typhoon about `TestBarAssembly`, I was sort of expecting Typhoon to help me inject `TestBarAssembly` into the `barAssembly` property. What am I doing wrong?

p.s. I'm not using plist integration at all.

**Comment by fatuhoku** [comment]
Ah. I think it must be because  `BarAssembly` is a protocol; and declaring the property `    var barAssembly: BarAssembly!` is not something Typhoon will pick up on to try to inject. If it were a concrete `TyphoonAssembly` subclass however Typhoon would probably inject as usual.

**Comment by jasperblues** [comment]
Hi @fatuhoku, as we say here: https://github.com/appsquickly/Typhoon/wiki/Modularizing-Assemblies

 . . . in the assembly you need to declare it as a `TyphoonAssembly<SomeProtocol>` . . anywhere you can just use the protocol.

**Comment by fatuhoku** [comment]
@jasperblues yes, I would have guessed that's how you'd write it. But The problem is that there's no equivalent of `Class <Protocol>` syntax in Swift. I.e. You cannot write a type annotation that constrains both class and protocol for a symbol.

I guess the only advisable way is to write `TyphoonAssembly`, and then when it is used, force downcast into the protocol. Not nice, but I'll let you know if it works,

**Comment by fatuhoku** [comment]
Okay, tried to declare the variable as:

```swift
var barAssembly: TyphoonAssembly!
```

... and when I make use of `barAssembly` I force downcast:
                 initializer.injectParameterWith((self.barAssembly as! BarAssembly).barComponent())
```

But this does not work.

![screen shot 2015-09-12 at 09 11 53](https://cloud.githubusercontent.com/assets/430233/9830647/5fe2affe-592e-11e5-9195-fb71920e6c76.png)

It's clear that `TestBarAssembly` conforms to `BarAssembly` so ... what's happening here?

**Comment by fatuhoku** [comment]
I suggest we fix this problem by extracting a protocol from `TyphoonAssembly` class, and call it  `TyphoonAssemblyProtocol`.

Then when Typhoon introspects an assembly for any collaborating assemblies, instead of just looking for properties that are declared as `TyphoonAssembly` it should also look for properties that apparently conform to `TyphoonAssemblyProtocol`.

This way, collaborating assemblies backed by custom protocols can be declared naturally by using [Swift's protocol composition syntax](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Types.html#//apple_ref/doc/uid/TP40014097-CH31-ID454):

For my example above, I would write:
```
var barAssembly: protocol <TyphoonAssemblyProtocol, BarAssembly>
```

... and Typhoon should inject the hell out of it!

**Comment by jasperblues** [comment]
@fatuhoku Would you like to try a PR?

**Comment by fatuhoku** [comment]
@jasperblues I would love to, I wouldn't know where to start and I've got a workaround — writing a few lines of initialisation code! It's definitely something I would look at if it were a priority.

**Comment by NailxSharipov** [comment]
I guess I has found a solution for this problem. You could creat an optional protocol for your assembly and an empty TyphoonAssembly class, which is implement it.
In your case it will be look like:
`import Foundation
import Typhoon

@objc
protocol BarAssembly {
    optional func barComponent() -> AnyObject 
}

------------------------------

import Foundation
import Typhoon

// hack for Typhoon framework
public class BarTyphoonAssembly: TyphoonAssembly, BarAssembly {}

------------------------------

import Foundation
import Typhoon

class FooAssembly : TyphoonAssembly {
    var barAssembly: BarTyphoonAssembly!
    func fooComponent() {
        return TyphoonDefinition.withClass(FooComponent.self) {
            (definition) in
            definition.useInitializer("initWithBar:") {
                 (initializer) in
                 initializer.injectParameterWith((self.barAssembly as! BarAssembly).barComponent!())
            }
        }
    }
}`

**Comment by etolstoy** [comment]
Looks like @NailxSharipov has a solution. However, we strongly recommend to use the [pure Swift version](https://github.com/appsquickly/TyphoonSwift) of Typhoon.
