### ISSUE TITLE
Extra NSLog() calls in some of the classes

### ISSUE THREAD

**Issue by igrekde** [appsquickly/Typhoon#420]
I've accidentally found the `NSLog()` calls in some of the classes: `TyphoonComponentFactory`, `TyphoonDefinition+InstanceBuilder`, `TyphoonViewHelpers`. To have the ability of choosing the specific log level and disabling this calls we've got to replace them with `OCLogTemplate` macros.

**Comment by jasperblues** [comment]
Yes please. We might also want to embed OCLogTemplate in the code rather than use a git submodule - you can't more "quality" points in CocoaPods this way, I think.
