### ISSUE TITLE
When a Swift assembly is injected into a Objective-C object (via autoinjection), it returns TyphoonDefinitions at runtime.

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#421]
I recently started building new features with Swift. I create a Swift Typhoon assembly to wrap it up called `NewFeatureAssembly`.

When I do

```objc
@interface RootWireframe ()
@property(nonatomic, strong) InjectedClass(NewFeatureAssembly)newFeatureAssembly;
// ...
@end

@implementation

- (void)mainInterface {
        UITabBarController *tabViewController = [UITabBarController new];
        tabViewController.viewControllers = @[
                [self.newFeatureAssembly viewController];
        ];

       return tabViewController;
}
@end
```

I get an error that looks like this:

```objc
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TyphoonDefinition _setViewHostsLayoutEngine:]: unrecognized selector sent to instance
```

This is because `[self.newFeatureAssembly viewController];` isn't returning a real `UIViewController`, but is in fact returning a `TyphoonDefinition` instead.

In order to incorporate my new Swift feature, I'll now either have to manually instantiate the components manually, or translate the Objective-C unit that's being injected into into Swift as well.

**Comment by jasperblues** [comment]
@fatuhoku It sounds like the assembly is not activated.

**Comment by fatuhoku** [comment]
@jasperblues quite right — I could have sworn I added the TyphoonAssembly entry into the plist. I  must have forgotten.  Thanks!

**Comment by fatuhoku** [comment]
@jasperblues It turns out that when `TyphoonDefinition` are returned, this is not only a symptom of the `TyphoonAssembly` not having been activated, but also that the component as not marked as `dynamic`. I totally forgot `dynamic` and stressed myself out!   Lots of example code here: https://github.com/appsquickly/Typhoon-Swift-Example/blob/aa28d586f13da12358526c5fd25a7e0166216e6b/PocketForecast/Assembly/ApplicationAssembly.swift

**Comment by jasperblues** [comment]
@fatuhoku ahhhh. that is not good. I think if we replace instrumentation to use NSProxy we could fix that.
