### ISSUE TITLE
Fix module.modulemap file

### ISSUE THREAD

**Issue by pomozoff** [appsquickly/Typhoon#423]
There is a bug in this file.
It should looks like this one:

```
framework module Typhoon {
  umbrella header "Typhoon.h"

  export *
  module * { export * }

  explicit module OCLogTemplate {
    header "OCLogTemplate.h"
    link "OCLogTemplate"
    export *
  }
  explicit module TyphoonInstancePostProcessor {
    header "TyphoonInstancePostProcessor.h"
    link "TyphoonInstancePostProcessor"
    export *
  }
}
```
Otherwise Clang warnings:
> Umbrella header for module 'Typhoon' does not include header 'OCLogTemplate.h'
> Umbrella header for module 'Typhoon' does not include header 'TyphoonInstancePostProcessor.h'

I can't find how to fix it.

**Comment by igrekde** [comment]
Seems to be fixed by two steps:
- Added the `TyphoonInstancePostProcessor.h` to umbrella header file
- Changed the visibility level of `OCLogTemplate.h` from Public to Project.
