### ISSUE TITLE
How to use Typhoon in framework project

### ISSUE THREAD

**Issue by xujialiang** [appsquickly/Typhoon#427]
i want to use it in framework project , but I don't know how to init it with plist ?
or I have to init typhoon assembly by myself?

**Comment by jasperblues** [comment]
Here's an example of an app that uses plist integration to init Typhoon: 

https://github.com/appsquickly/Typhoon-example

Try building that. 

You can also use the manual init like in the quick start, but plist integration is recommended.

**Comment by xujialiang** [comment]
my project is static library. I set TyphoonInitialAssemblies in Info.plist, but...it don't work..

**Comment by jasperblues** [comment]
Do you have -ObjC and -all_load compiler flags set?

**Comment by xujialiang** [comment]
yes, I have set -ObjC and  -all_load, but assembly not init by Typphoon...
