### ISSUE TITLE
TyphoonPatcher is not available via Carthage built framework

### ISSUE THREAD

**Issue by baek-jinoo** [appsquickly/Typhoon#434]
I am trying to patch the assembly in my spec, but I am having trouble. Because I can't seem to create a instance of TyphoonPatcher as my project does not recognize it, while I can create TyphoonAssembly instances in the same file. I have a swift project in Xcode 7.0.1, and created the Typhoon framework v3.3.3 using Carthage command `carthage update --platform ios`. This problem does not exist when I use Cocoapods with `use_frameworks!`.

**Comment by jasperblues** [comment]
@baek-jinoo Thanks for reporting, and sorry for the delay in reply. Will fix ASAP.

**Comment by baek-jinoo** [comment]
Thanks for looking into it.
