### ISSUE TITLE
No code-level control exists to control logging verbosity

### ISSUE THREAD

**Issue by joshavant** [appsquickly/Typhoon#435]
The new logging in TyphoonConfigPostProcessor can only be modulated by OCLogTemplate-defined preprocessor macros ([link](https://github.com/appsquickly/Typhoon/blob/master/Source/Configuration/ConfigPostProcessor/TyphoonConfigPostProcessor.m#L131)).

It would be nice to make this controllable at a code-level (as opposed to preprocessor-level). This would support Cocoapod + Carthage workflows, where build settings are automatically generated.

Currently, to control this, my workflow would have to be:
-Update my project's dependencies
-Configure the Typhoon Xcode subproject's build settings to have the specific preprocessor macro
...and I'd have to remember to re-apply my settings, anytime the Xcode dependency subproject gets regenerated.

I've noticed this logging is particularly a problem in testing, where Assemblies might be stood up and torn down hundreds of times in succession (resulting in lots of console spew).

**Comment by joshavant** [comment]
For those that come across this issue and are wondering about a workaround...

The following works for Cocoapods installations. Add this to your `Podfile`:
```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      if target.name == "Typhoon"
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'LOGGING_LEVEL_INFO=0'
        end
      end
    end
  end
```
This requires **Cocoapods 0.38 or newer**, due to breaking changes in the APIs used in this code ([more here](http://blog.cocoapods.org/CocoaPods-0.38/#breaking-change-to-the-hooks-api)).

If you have Cocoapods older than 0.38, you might want to try this (untested!!):
```
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
      if target.name == "Typhoon"
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'LOGGING_LEVEL_INFO=0'
        end
      end
    end
  end
```

Not sure if it matters, but I'm using the `use_frameworks!` option in my Podfile.

Also, just to be sure, the above snippet of code does not check if there's an existing preprocessor value for `LOGGING_LEVEL_INFO`. You'll need to refactor that if you may have an existing value (but that seems like an exceedingly rare situation).

**Comment by igrekde** [comment]
@joshavant Thanks for reporting - right now modifying the Typhoon project settings via the Podfile is the only way to turn the logging off.

We'll think about the way to fix this issue in one of the next releases. And, of course, if you want to make a PR we'll greatly appreciate it!

**Comment by igrekde** [comment]
@joshavant We've removed the `TyphoonConfigPostProcessor` logs for now - and still thinking of a better way of logging implementation. Thanks for posting the issue!
