### ISSUE TITLE
`performAfterInjections:` throws exception if instance is nil.

### ISSUE THREAD

**Issue by andrewjl** [appsquickly/Typhoon#438]
When I attempt call `performAfterInjections:` on a definition that occasionally returns as nil, I get the below exception. Since messaging nil is a no-op is it possible for the call to be a no-op as well?
```
        [NSException raise:NSInvalidArgumentException
                    format:@"Method '%@' not found on '%@'. Did you include the required ':' characters to signify arguments?",
```

**Comment by igrekde** [comment]
Hi, @andrewjl ! Sorry for the long reply - we'll fix the issue in a couple of days. Thanks for reporting!
