### ISSUE TITLE
Could not build Objective-C module 'Typhoon'

### ISSUE THREAD

**Issue by Flar49** [appsquickly/Typhoon#443]
Hello!

I'm trying to integrate the Typhoon via Carthage to my Swift-based project and i'm getting these errors when i'm trying to build my project:
http://take.ms/tgsQH

I've followed the Carthage's guide on framework integration precisely. 

Could you please give me some hint how to solve this problem?

P.S.
Carthage version: 0.10.0
Typhoon version: 3.4.1

**Comment by igrekde** [comment]
Hi, @Flar49 . Thanks for reporting, I'll investigate it immediately.

**Comment by igrekde** [comment]
@Flar49 that was our problem - and it's fixed now. The new version will be released ASAP, meanwhile you can use `github "appsquickly/Typhoon" "master"` in your `Cartfile`.

And thanks for reporting - you've helped a lot of our users! 🎉

**Comment by Flar49** [comment]
@igrekde thanks Egor, i appreciate the fast response and fix :)

**Comment by poborin** [comment]
Looks like the same issue appeared again:

```
While building module 'Typhoon' imported from /Users/poborin/projects/intelematics/ios-bt-danlaw-driver/BLEDanlawClient/BLEDanlawClient/BLEDanlawClient.h:11:
In file included from <module-includes>:1:
In file included from /Users/poborin/projects/intelematics/ios-bt-danlaw-driver/BLEDanlawClient/../Carthage/Build/iOS/Typhoon.framework/Headers/Typhoon.h:23:
In file included from ../Carthage/Build/iOS/Typhoon.framework/Headers/TyphoonAssembly.h:12:
../Carthage/Build/iOS/Typhoon.framework/Headers/TyphoonDefinition.h:16:9: fatal error: 'TyphoonDefinitionNamespace.h' file not found
#import "TyphoonDefinitionNamespace.h"
        ^
1 error generated.
In file included from /Users/poborin/projects/intelematics/ios-bt-danlaw-driver/BLEDanlawClient/BLEDanlawClient/BLEDanlawClient.m:9:
/Users/poborin/projects/intelematics/ios-bt-danlaw-driver/BLEDanlawClient/BLEDanlawClient/BLEDanlawClient.h:11:9: fatal error: could not build module 'Typhoon'
@import Typhoon;
```
