### ISSUE TITLE
Documentation on Swift?

### ISSUE THREAD

**Issue by AAverin** [appsquickly/Typhoon#448]
Is there documentation updated to Swift syntax?

**Comment by jasperblues** [comment]
Unfortunately only the Quick Start guide for Swift. It would be good to provide Swift examples alongside ObjC in the user guide.

**Comment by AAverin** [comment]
That would be very nice - with Swift there will be many people who will have troubles understanding ObjC

**Comment by jasperblues** [comment]
You still might need to know _something_ of ObjC (not necessarily the syntax) because Typhoon uses the ObjC runtime. So there'd be similar rules as, say, using KVO. 

Perhaps we'll release a pure Swift DI container in future, meanwhile Typhoon is recommended.

**Comment by AAverin** [comment]
Well, I just started doing iOS on Swift and I don't really know objC syntax that good to figure out how DI container really works and write the same thing on Swift. Thus the question - documentation on Swift will be more helpful for guys like me

**Comment by jasperblues** [comment]
:+1: Understood - will do ASAP.

**Comment by AAverin** [comment]
Great, thanks a lot!

**Comment by etolstoy** [comment]
We strongly recommend to use the [pure Swift version](https://github.com/appsquickly/TyphoonSwift) of Typhoon.
