### ISSUE TITLE
Improve logging capabilities

### ISSUE THREAD

**Issue by etolstoy** [appsquickly/typhoon#450]
A nice to have feature is the ability to control logging levels in the runtime. A good example of such feature is `MagicalRecord` - https://github.com/magicalpanda/MagicalRecord/blob/master/MagicalRecord/Core/MagicalRecordLogging.h.

**Comment by vasilenkoigor** [comment]
@etolstoy @alexgarbarev @jasperblues 
I'd want to implement this feature, if you don't mind 👍

**Comment by alexgarbarev** [comment]
@vasilenkoigor sure, go ahead! (i've never used Typhoon logging at all, though..)

**Comment by etolstoy** [comment]
@vasilenkoigor how is the progress with this issue?
