### ISSUE TITLE
Does Typhoon work in Apple Watch extension?

### ISSUE THREAD

**Issue by HiveHicks** [appsquickly/Typhoon#452]
I haven't found any info on the subject in the docs.

**Comment by igrekde** [comment]
Hi, @HiveHicks! We haven't done anything special to support Apple Watch, but it seems that Typhoon should work as is. We would be very grateful if you give it a try and report about any found issues 🙂

**Comment by HiveHicks** [comment]
What I was especially interested in is the preferred integration method when using Typhoon in Watch extension. Obviously, plist integration won't work (or will it?). So, I still can't see any way of injecting components to Interface Controllers.

**Comment by igrekde** [comment]
@HiveHicks I haven't created any watchOS apps before, so it will take some time to investigate. By the way, are you speaking about watchOS 1 or 2?

**Comment by HiveHicks** [comment]
@igrekde I'm speaking about both. I've managed to get it working by using manual activation. For that I had to manually create singleton instance of an assembly in watchOS 1 (because there isn't any delegate object for an extension):

```
+ (instancetype)sharedAssembly
{
    static WatchAssembly *assembly;
    static dispatch_once_t once;

    dispatch_once(&once, ^{
        assembly = [WatchAssembly assembly];
        [[TyphoonAssemblyActivator withAssemblies:@[assembly]] activate];
    });

    return assembly;
}
```

I suppose that in watchOS 2 (where a delegate for an extension exists) you can activate an assembly when extension launches and make it default.

Now, in all my controllers I have to refer to `[WatchAssembly sharedAssembly]`, which strongly couples all the code with Typhoon and I don't like it much, but I can't see any alternative as for now.

**Comment by igrekde** [comment]
@HiveHicks Maybe you can improve your approach a little by using `+ defaultFactory` and `+ makeDefault` methods from `TyphoonComponentFactory` class:

```objc
TyphoonComponentFactory *factory = [TyphoonBlockComponentFactory factoryWithAssembly:[WatchAssembly assembly]];
[factory makeDefault];
```

This factory can be used throughout your extension by calling `[TyphoonComponentFactory defaultFactory]`:
```objc
WatchAssembly *assembly = (WatchAssembly *)[TyphoonComponentFactory defaultFactory];
```

Still not even close to a nice solution, but you won't have to use the singleton.

**Comment by pkrmf** [comment]
I pulled Typhoon and  added a few #if TARGET_OS_WATCH flags on some of the classes that are not supported by watch. I am currently using it on Watch targets and it works just fine.

Obviously I had to remove support the support to storyboards on watch and I had to exclude some of the classes that are related to UIKit.

**Comment by etolstoy** [comment]
@pkrmf We would be glad to accept these changes as a PR!
