### ISSUE TITLE
Parent definition with before/after injections

### ISSUE THREAD

**Issue by Emailrus** [appsquickly/Typhoon#458]
Not sure if it's by design, but it seems that `TyphoonDefinition+InstanceBuilder` doesn't take into account beforeInjections and afterInjections of parent definitions.

I wanted to have something like this:

```objective-c
- (id<IViewModel>)parentViewModel
{
    return [TyphoonDefinition withClass:[BaseViewModel class]
                          configuration:^(TyphoonDefinition *definition)
    {
        definition.abstract = YES;
        [definition performAfterInjections:@selector(myAfterInjectionMethod)];
    }];
}

- (id <IProfileViewModel>)profileViewModel
{
    return [TyphoonDefinition withParent:[self parentViewModel]
                                   class:[ProfileViewModel class]];
}

```

But `myAfterInjectionMethod` is never called

**Comment by igrekde** [comment]
@Emailrus, the [wiki](https://github.com/appsquickly/Typhoon/wiki/Types%20of%20Injections) says:
```
From its parent, a definition will inherit the initializer, property injections, method injections and scope. Any of these can be overridden.
```
So, its by design. However, I'm not very familiar with this piece of functionality, so we need @jasperblues and @alexgarbarev to debate about this feature request.

**Comment by jasperblues** [comment]
:+1: I think it is an oversight that berfore/after injections are not inherited from the parent.

**Comment by alexgarbarev** [comment]
:+1:
