### ISSUE TITLE
Carthage installation for OS X

### ISSUE THREAD

**Issue by jozsef-vesza** [appsquickly/Typhoon#459]
I would like to use Typhoon in an OS X app I'm building. Carthage installation works well for iOS targets, but seems unavailable for OS X.

Invoking the command:
`carthage update --platform Mac`

Yields the following message:
`Dependency "Typhoon" has no shared framework schemes for any of the platforms: Mac`

Is there a simple way to integrate Typhoon into an OS X app? It doesn't appear to have a regular Cocoa framework build scheme.

**Comment by jasperblues** [comment]
@jozsef-vesza Sorry that was an oversight. Will fix ASAP. In the meantime you can: 

* Install via CocoaPods
* Drag the source files into your project.

**Comment by jozsef-vesza** [comment]
@alexgarbarev I still have to investigate this one: the Cocoa framework I added is functional (I am using it in a project), but `carthage update` hangs. My guess is that it can't figure out which scheme to build.

**Comment by jozsef-vesza** [comment]
@jasperblues @alexgarbarev pretty sure this can be closed.

**Comment by andrewkboyd** [comment]
Am I missing something on this one?
`carthage update --platform Mac`

Still gives me the same error noted in this Issue.

I just started using Carthage as CocoaPods was slowing things down for me, so I might be overlooking something.  The Typhoon-OSX target is there in the xcodeproj that Carthage checks out, but carthage seems to be unable to build the Mac version.

`Dependency "Typhoon" has no shared framework schemes for any of the platforms: Mac` 

Thoughts?

**Comment by jozsef-vesza** [comment]
My change might not be in the latest tag yet (3.4.5)? You could try putting ```github "appsquickly/Typhoon"
 master``` in your Cartfile?

**Comment by andrewkboyd** [comment]
That did it.  

Rookie mistake. Thanks!
