### ISSUE TITLE
Set a context pool before assembling an instance

### ISSUE THREAD

**Issue by froschohr** [appsquickly/Typhoon#460]
Hi,
I already tried to explain my needs here:
http://stackoverflow.com/questions/34167321/extent-existing-objectgraphs-with-typhoon?noredirect=1#comment56083292_34167321

Sometimes it would be handy to put some objects in a component pool before starting assembling an instance.
Something like this:

```
MiddleAgesAssembly* assembly = [[MiddleAgesAssembly assembly] activate];
id<TyphoonComponentsPool> objectGraphSharedInstances = [assembly valueForKeyPath:@"factory._objectGraphSharedInstances"];
[objectGraphSharedInstances setObject:castle forKey:@selector(castle)];
[assembly knight];
```

Suppose the definition of basicKnight has a new scope called TyphoonScopeContext.
The usage could look like this:

```
id<TyphoonComponentsPool> ctx1 = (id<TyphoonComponentsPool>)[[NSMutableDictionary alloc] init];
id<TyphoonComponentsPool> ctx2 = (id<TyphoonComponentsPool>)[[NSMutableDictionary alloc] init];

middleAgesAssembly.contextPool = ctx1;
Knight *knight1 = [middleAgesAssembly basicKnight];

middleAgesAssembly.contextPool = ctx2;
Knight *knight2 = [middleAgesAssembly basicKnight];

middleAgesAssembly.contextPool = ctx1;
assert( [middleAgesAssembly basicKnight] == knight1);

middleAgesAssembly.contextPool = ctx2;
assert( [middleAgesAssembly basicKnight] == knight2);
```

What do you think about the idea of a new scope "TyphoonScopeContext" and the possibility to exchange the corresponding component pool from the outside?

**Comment by jasperblues** [comment]
Ah now that I think of it, it would be possible to do something like you want by:

**Comment by froschohr** [comment]
Ok, I understand what you mean. 
That 's a clever setup. 
And yes, it would solve the problem. 

The drawback is, that now the consumer of the knight-instance is responsible for the scope/pool the knight is living in.
In my example above, the scope of the knight was part of the knight-definition.
So, I still like the idea about an explicit scope.

But I have to admit, messing around mit component-pools is not a very user-friendly api.

I tested something like this:

    MiddleAgesAssembly* assembly = [[MiddleAgesAssembly assembly] activateWithCollaboratingAssemblies:@[ctx1, ctx2]];

Now each of the three assemblies holds a private component-pool. Right before forwarding an invocation to the factory, the assembly passes this component pool to the factories context-component-pool.

The result is a assembly-wide singelton.
The usage looks like this:

    Knight *knight1 = [ctx1 basicKnight];
    Knight *knight2 = [ctx2 basicKnight];

    assert( [ctx1 basicKnight] == knight1);
    assert( [ctx2 basicKnight] == knight2);

**Comment by etolstoy** [comment]
The issue has a workaround described by @jasperblues.
