### ISSUE TITLE
TyphoonDefinitionNamespace.h missing in Carthage build

### ISSUE THREAD

**Issue by j4n0** [appsquickly/Typhoon#461]
I'm getting `'TyphoonDefinitionNamespace.h' file not found` after building with Carthage.

If I open Carthage/Checkouts/Typhoon/Typhoon.xcodeproj I don't see TyphoonDefinitionNamespace.h in the Build Phases > Public > Headers of the Typhoon framework.

Including such header and running `carthage build --platform ios` fixes the issue. Thus, it seems that the header should be added.

**Comment by igrekde** [comment]
Hi, @j4n0! Thanks for reporting, this issue has already been fixed by [this PR](https://github.com/appsquickly/Typhoon/pull/453). We haven't released a new version, so you can use:
`pod 'Typhoon', :head` for now.
