### ISSUE TITLE
TyphoonConfig(key) return not updated value from application settings plist

### ISSUE THREAD

**Issue by spbvasilenko** [appsquickly/Typhoon#465]
Hey everyone!

Recently I’ve found some issue with Typhoon Configuration related to plists with default values. My application has dev settings which are used by testers for changing environment URL (production/sandbox, etc). These settings are stored in Settings.bundle within Xcode workspace. Settings.bundle contains defaultSettings.plist which stores values from dev settings. defaultSettings.plist is connected to Typhoon in order to use TyphoonConfig(key) method.
So, when I enter some new value into dev settings and restart application, TyphoonConfig(key) method gives me old value, not new one just entered.
What is wrong with my configuration?

**Comment by igrekde** [comment]
Hi, @spbvasilenko! Can you provide a code for modifying your `plist` file?

**Comment by spbvasilenko** [comment]
Thanks for your answer, @igrekde. But recently I'm convinced that this is not a bug. When I enter some new value into dev settings, they stores not in plist. New values stores in NSUserDafaults. You can close this issue. Sorry :)

**Comment by igrekde** [comment]
Great! Feel free to reopen the issue if you encounter it again!
