### ISSUE TITLE
VCS Collaborating Workflow

### ISSUE THREAD

**Issue by oligazar** [appsquickly/Typhoon#466]
I with friend of mine run into some problems when trying to work on the same swift project through bitbucket.org. Every time after committing and pushing changes on my side and pulling on his side he gets warning that he is unable merge changes and he first need to discard some local changes. After he resolves somehow the problem and made new commit-push the same story repeats on my side. 
Then we tried to share the project through drop box. But every rimes he make changes I was unable to run project because of errors like "TyphoonAssembly.h not found", or "TyphoonAssembly has duplicate" or something like that. After that I run pod update and project on my side runs well, but on his side he got new errors.
I've already seen [this post] (https://github.com/appsquickly/Typhoon/issues/59) but I'm still not clear what is the recommended workflow and how to avoid or deal with such issues. Thanks in advance and sorry for my english.

**Comment by jasperblues** [comment]
Hi @oligazar !

Thanks for opening an issue, however StackOverflow is the place to discuss usage problems like the one you're having. 

If during that process we discover a bug or good candidate for a new featuer, we can open an issue here on Github :)

Thanks for using Typhoon!
