### ISSUE TITLE
Missig file in generated framework by Carthage 

### ISSUE THREAD

**Issue by gorgaborjozsef** [appsquickly/Typhoon#471]
I'm try to using typhon framework with carthage, but the generated framework is not contains "TyphoonDefinitionNamespace.h" file and the xcode build failed. Can you add the file into typhoon target with public modifier?

**Comment by igrekde** [comment]
Hi! Sorry for a long reply - it's a known issue and has already been fixed. We haven't released a new version yet, so you can use master branch for now.

**Comment by gorgaborjozsef** [comment]
Ok, thanks for reply.
