### ISSUE TITLE
TyphoonObjectMatcher does not behave as expected

### ISSUE THREAD

**Issue by gferreri** [appsquickly/Typhoon#473]
I want to create a definition that returns one object or another at runtime depending on the value of a flag. Here's a simple example:

```
public class MyAssembly : TyphoonAssembly {
    
    private func useMockApiService() -> Bool {
        return NSUserDefaults.standardUserDefaults().boolForKey("useMockService")
    }

   public dynamic func realApiService() -> AnyObject {
        return TyphoonDefinition.withClass(ApiServiceImpl.self) 
    }
    
    public dynamic func mockApiService() -> AnyObject {
        return TyphoonDefinition.withClass(MockApiServiceImpl.self)
    }


   public dynamic func myDataService() -> AnyObject {
        return TyphoonDefinition.withOption(useMockApiService(), 
                yes: self.mockApiService(), 
                no: self.realApiService())
    }
```

This works for the *first* injection of _myDataService_ only. All subsequent injections of _myDataService_ will use the same value for the option. In other words, Typhoon only evaluates the value of the options once, when the Assembly is being initialized, and *not* at run time as the documentation suggests. How do I construct a scenario where _useMockService()_ is called at run-time to decide which definition to use to satisfy the dependency?

**Comment by jasperblues** [comment]
You want <a href="https://github.com/appsquickly/Typhoon/wiki/Typhoon-Option-Matcher">Typhoon Option Matcher</a>. If something is not clear, pls open a new question on StackOverflow or an issue here, as appropriate.

**Comment by gferreri** [comment]
Sorry, but maybe you misread my comments. I'm already using Typhoon Option Matcher, as you can see in the snippet above, but it doesn't behave as expected.

**Comment by alexgarbarev** [comment]
That's because your method:
```
    private func useMockApiService() -> Bool {
        return NSUserDefaults.standardUserDefaults().boolForKey("useMockService")
    }
```
It's static and called only once, while building assembly. 
Instead of returning bool here, you should return TyphoonDefinition, which composes Bool, like that:

```
public dynamic func useMockApiService() -> AnyObject {
        return TyphoonDefinition.withFactory(NSUserDefaults.standardUserDefaults(), selector: "useMockService")
}
```

**Comment by gferreri** [comment]
Thanks for the suggestion. Unfortunately, it still doesn't work. I modified it slightly to the following

```
 private dynamic func useMockDataService() -> AnyObject {
        return TyphoonDefinition.withFactory(NSUserDefaults.standardUserDefaults(), selector: "boolForKey:"){
            i in
            i.injectParameterWith("useMockDataService")
        }
    }
```
But the app crashes with a EXC_BAD_ACCESS  from within this method in _NSInvocation+TCFInstanceBuilder.m_:

```
- (id)typhoon_resultOfInvokingOn:(id)instanceOrClass NS_RETURNS_RETAINED
{
    id returnValue = nil;

    BOOL isReturnsRetained = typhoon_IsSelectorReturnsRetained([self selector]);
    [self invokeWithTarget:instanceOrClass];
    [self getReturnValue:&returnValue];
    if (!isReturnsRetained) {
        [returnValue retain]; /* Retain to take ownership on autoreleased object */ // <== CRASH HERE
    }

    return returnValue;
}
```

I found another solution that simply uses _withFactory_ to return the proper instance at runtime, and no longer uses the option matcher.

**Comment by alexgarbarev** [comment]
Yes, you shouldn't return bool by that factory definition, you should return NSNumber with bool inside instead. Typhoon doesn't support scalars directly, but is uses NSNumber wrappers instead (and smartly unwrap if necessary)

Does my suggestions works?

Отправлено с iPhone
