### ISSUE TITLE
TVOS support

### ISSUE THREAD

**Issue by Air7Y** [appsquickly/Typhoon#495]
Please can you add Typhoon.podspec to support TVOS ?
**spec.platform     = :tvos, '9.0'**
Now the only way we can use Typhoon in our project is by cloning the repo and make changes in .podspec
http://stackoverflow.com/questions/36376210/is-there-a-way-to-use-typhoon-di-in-tvos-apps/36377604#36377604
Thanx a lot!

**Comment by etolstoy** [comment]
Hi, @Air7Y. Sorry for the long reply. I believe that issue is fixed by #503.
