### ISSUE TITLE
Need Help understanding run-time propagation

### ISSUE THREAD

**Issue by wh33ler** [appsquickly/Typhoon#496]
In my application I use a lot of run-time arguements and now it seems to get out of hand.

currently I call run time objects from the assembly directly which now gets into too many classes in my opinion.
I looked at the example (Propagating run-time arguments through to dependencies)
But I don't really understand how it works. Could someone please write how this example is used to setup objects. Does it mean that the view gets the run-time object from a selector of the controller which should be there (not defined) ?? I am so confused... sry.

**Comment by etolstoy** [comment]
Hi, @wh33ler . If you still have this question - feel free to create a question using `Typhoon` tag on [StackOverflow](http://stackoverflow.com/questions/tagged/typhoon?sort=newest&pageSize=15).
