### ISSUE TITLE
Allow Assembly to have other Properties other than Assemblies.

### ISSUE THREAD

**Issue by pkrmf** [appsquickly/typhoon#500]
When the assembly gets instantiated all its properties get instantiated as well, but they are being treated as Assemblies. It would be perfect if before doing that there was an if statement checking for the class type of every property of the Assembly. If the property is a subclass of TyphoonAssembly then yeah, go ahead and treat it as a collaborating assembly.

**Comment by pkrmf** [comment]
I forgot to add the why of the usage of properties that aren't assemblies in a Assembly:

http://stackoverflow.com/questions/37095549/typhoonassembly-not-assembling-objects-provided-as-property.

I can provide the fix if you guys desire.

**Comment by knox** [comment]
I am trying to migrate my project from Typhoon 3.4.5 to 4.0.2 and just bumped into this issue, too. In my assembly i have one property which type is no assembly and that used to work well with the old version but it does not work any longer. Any hints on that?

**Comment by daria-kopaliani** [comment]
+1 for assembly properties.

**Comment by jasperblues** [comment]
This is stale, so I'm closing this. Please check out pilgrim.ph (pure swift successor to Typhoon) which allows assembly properties, other than collaborating assemblies.
