### ISSUE TITLE
Overriding method in assembly causes duplicate registration

### ISSUE THREAD

**Issue by daria-kopaliani** [appsquickly/Typhoon#506]
Hi, I think I still have an issue related to [this closed one](https://github.com/appsquickly/Typhoon/issues/345#event-359353151).
I need to make several “white labels“, so I need to have several assemblies which differ only in few classes. I decided to have a “WhiteLabel1AppAssembly” and  “WhiteLabel2AppAssembly” and they both have a collaborating “DefaultAssembly” to get most of their dependencies from there. But I get the same exception.

    @implementation WhiteLabel1AppAssembly

        - (id<BEAlbumWireframeFactory>)albumWireframe {

            return [self.defaultAssembly defaultAlbumWireframe];
        }

    @end

    @implementation DefaultAssembly

        - (id)defaultAlbumWireframe {
   
                return [TyphoonDefinition withClass:... configuration:^(TyphoonDefinition *definition) {
        ...
                }];
        }
    @end

**Comment by alexgarbarev** [comment]
Hi Daria,
Try this approach:
```
    - (id)albumWireframe { return [TyphoonDefinition with:[self.defaultAssembly defaultAlbumWireframe]]; }

```
Basically you cannot register same definition twice, but you can register reference to it using example from above

**Comment by daria-kopaliani** [comment]
Thank you, this solves all my problems.

**Comment by alexgarbarev** [comment]
Glad to hear!
