### ISSUE TITLE
Typhoon doesn't read .plist files properly when it's installing via carthage

### ISSUE THREAD

**Issue by dvs15** [appsquickly/Typhoon#508]
When I'm trying to switch installing Typhoon from Pods to Carthage, I got issue with loading our TyphoonGlobalConfig files.

This is happens because when you install Typhoon via Carthage, typhoon placed in it's own bundle Typhoon.framework and code `NSBundle *bundle = [NSBundle bundleForClass:[self class]];` will return Typhoon.framework bundle instead of my project main bundle.

I see two way how to solve this:

Fast
1. Switch `[NSBundle bundleForClass:[self class]]` to `[NSBundle mainBundle]` in places where Typhoon trying to load external resources. 

Correct way
2. Add param "externalResourceBundle" (make it by default as mainBundle of the project) and use this bundle everywhere to load external resources.

**Comment by vasilenkoigor** [comment]
Hello @dvs15! 
Thanks for reporting 👍 

I'm suggest fix like 
```
[NSBundle bundleForClass:[delegate class]]
```
Because it’s swizzle for AppDelegate. And I think we should to use bundle for delegate class :)

**Comment by vasilenkoigor** [comment]
Hi @dvs15!
Fix was merged into master, please update to Carthage framework and make check 👍
