### ISSUE TITLE
want to study it,but has no demo to show~~

### ISSUE THREAD

**Issue by DaisukeZJY** [appsquickly/Typhoon#515]

**Comment by vasilenkoigor** [comment]
Hello @DaisukeZJY 
You can find examples in this place
![screen shot 2016-07-11 at 14 15 09](https://cloud.githubusercontent.com/assets/7735730/16728934/6fb534b6-477a-11e6-969f-b698e2c55680.png)

**Comment by DaisukeZJY** [comment]
THANKS
