### ISSUE TITLE
Duplicate Interface definition for class Typhoon Method

### ISSUE THREAD

**Issue by sgup77** [appsquickly/Typhoon#520]
After updating my cocoapods i am getting lot of errors

1.) Duplicate interface definition for class TyphoonMethod
2.) Redifinition of Typhoonscope
3.) Redifinition of enumerator 'TyphoonScopePrototype'

**Comment by alexgarbarev** [comment]
@sgup77 try to do clean build. Check if it happens with other pods

**Comment by sgup77** [comment]
<img width="292" alt="screen shot 2016-07-21 at 12 05 39 am" src="https://cloud.githubusercontent.com/assets/5609616/16998446/125a68ae-4ed7-11e6-8a42-0c099d9b4e59.png">

Clean not working...

**Comment by vasilenkoigor** [comment]
Hi @sgup77
Problem was solved?

**Comment by sgup77** [comment]
yes , it is resolved.
i was using both objective c and swift Assembly files in my project with pods 7.0 . But when i updated my pods to 8.0. It started giving me above problems. so i have ported all my objective c assembly files to swift and problem is resolved.

**Comment by vasilenkoigor** [comment]
@sgup77 Great! Thanks for answer :)
