### ISSUE TITLE
Typhoon no longer thread safe again in newest version

### ISSUE THREAD

**Issue by leimingdu** [appsquickly/Typhoon#521]
Hi, 

Currently, I meet a lot of crush by typhoon after I introduce multi-threading in my APP.

Fatal Exception: NSRangeException
0  CoreFoundation                 0x1847542d8 **exceptionPreprocess
1  libobjc.A.dylib                0x195f280e4 objc_exception_throw
2  CoreFoundation                 0x184754218 -[NSException initWithCoder:]
3  Foundation                     0x18557379c -[NSString rangeOfString:options:range:locale:]
4  sswdOnline                     0x100318d78 -[TyphoonTypeDescriptor initWithTypeCode:](TyphoonTypeDescriptor.m:101)
5  sswdOnline                     0x100318bd4 +[TyphoonTypeDescriptor descriptorWithTypeCode:](TyphoonTypeDescriptor.m:69)
6  sswdOnline                     0x10030fe2c +[TyphoonIntrospectionUtils typeForPropertyNamed:inClass:](TyphoonIntrospectionUtils.m:48)
7  sswdOnline                     0x100309a0c -[TyphoonFactoryAutoInjectionPostProcessor autoInjectedPropertiesForClass:](TyphoonFactoryAutoInjectionPostProcessor.m:48)
8  sswdOnline                     0x1003097a8 -[TyphoonFactoryAutoInjectionPostProcessor postProcessDefinition:](TyphoonFactoryAutoInjectionPostProcessor.m:36)
9  sswdOnline                     0x100309730 -[TyphoonFactoryAutoInjectionPostProcessor postProcessDefinition:replacement:withFactory:](TyphoonFactoryAutoInjectionPostProcessor.m:29)
10 sswdOnline                     0x100302f94 -[TyphoonComponentFactory definitionAfterApplyingPostProcessorsToDefinition:](TyphoonComponentFactory.m:362)
11 sswdOnline                     0x100302e60 __46-[TyphoonComponentFactory applyPostProcessors]_block_invoke (TyphoonComponentFactory.m:349)
12 sswdOnline                     0x100302768 -[TyphoonComponentFactory enumerateDefinitions:](TyphoonComponentFactory.m:235)
13 sswdOnline                     0x100302e10 -[TyphoonComponentFactory applyPostProcessors](TyphoonComponentFactory.m:354)
14 sswdOnline                     0x100302ba8 -[TyphoonComponentFactory _load](TyphoonComponentFactory.m:321)
15 sswdOnline                     0x100301f9c -[TyphoonComponentFactory load](TyphoonComponentFactory.m:117)
16 sswdOnline                     0x1003024d4 -[TyphoonComponentFactory componentForKey:args:](TyphoonComponentFactory.m:190)
17 CoreFoundation                 0x18475a100 __invoking_**
18 CoreFoundation                 0x1846562fc -[NSInvocation invoke]
19 CoreFoundation                 0x18465ae30 -[NSInvocation invokeWithTarget:]
20 sswdOnline                     0x1002fe290 -[TyphoonBlockComponentFactory forwardInvocation:](TyphoonBlockComponentFactory.m:127)
21 sswdOnline                     0x1002f9278 -[TyphoonAssembly forwardInvocation:](TyphoonAssembly.m:107)

I saw a similar issue which opened in 2014, in that issue ,it said after upgrade to 2.X the issue will be fixed. However, I am using the newest version which installed using cocospods 3 month ago. After I switch back the single thread, the issue no long obvious. however, such approach have bring a big limitation for my app.

Can you give me some tips how to make typhoon thread safe.

[[[[[UCServiceAssembly assembly] activate]   is just the such way to get the instance of assembly.

Thanks in advance

//Leiming

**Comment by vasilenkoigor** [comment]
Hi @leimingdu!

Can you show code example how do you use assemblies between threads?
