### ISSUE TITLE
Typhoon load optimizing

### ISSUE THREAD

**Issue by vasilenkoigor** [appsquickly/Typhoon#522]
On WWDC 2016 session https://developer.apple.com/videos/play/wwdc2016/406/
Apple recommends replace `+(void)load` with `+(void)initialise`. In Typhoon framework I'm found the few places where used `+(void)load` method.
It will be a nice enhancement follow to new Apple recommendations.

**Comment by alexgarbarev** [comment]
+load is called earlier, and we use that to do something very early. 
+initialize called before first message sent. 

Hope this make sense

Отправлено с iPhone
