### ISSUE TITLE
Non-Thread Safe Property Injection

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [appsquickly/Typhoon#530]
Hi,

I've discovered a race condition when the property injection code is running in parallel. 

My first question, and I'm afraid of the answer :), is Typhoon thread safe ?

The code causing the issue is in TyphoonIntrospectionUtils.m line 33.

`        static char buffer[256];
`

There is no reason to be static and this is the root cause for random crashes we are facing on our app. 

If Typhoon is thread safe I'd be happy to remove the static keyword. Otherwise, I'm in trouble ...

Thanks in advance,

**Comment by alexgarbarev** [comment]
Yes, typhoon supposed to be threaded safe. It's guaranteed by wrapping all outside methods code into synchronized statement, so static inside should works.
Please review your typhoon usage, which two public methods works in parallel for you?


Отправлено с iPhone

**Comment by alexgarbarev** [comment]
Thank you for these details! I'll take a look later today then get back to you soon.

Best Regards,
Aleksey

**Comment by vitorhugomagalhaes** [comment]
Sure.

If you need more details, feel free to ask.

**Comment by alexgarbarev** [comment]
@vitorhugomagalhaes what's Typhoon version you using?

**Comment by vitorhugomagalhaes** [comment]
Hi,

Version 3.2.8 , maybe a bit old ...

Should I try the latest on ?

Thanks,

**Comment by vitorhugomagalhaes** [comment]
Hi,

I've being using the latest version without any crash. Cannot confirm if it really solves the issue or not.

Any feedback ?

BR,

**Comment by alexgarbarev** [comment]
Yes, I think there is still one issue in multi threading while using assembly interface. I will fix that asap.

Unfortunately these kind of problems can't be covered by unit tests or easily replicated, so we can only analyze the code. (Btw. If you have demo which shows that crash - it would be helpful) 

Best Regards,
Aleksey

**Comment by vitorhugomagalhaes** [comment]
Hi,

Demo is not easy. The project is quite big and it's difficult to isolate the specific code to replicate the behaviour.

Thanks,

**Comment by vitorhugomagalhaes** [comment]
Hi,

Just wondering if you have the time to check this.

Removing the static buffer seems to workaround. We will release to market next week so I'm bit short in time.

If you don't approve the static keyword removal I'll probably fork this for our selfs right now.

Any suggestion ?

Thanks in advance,

**Comment by alexgarbarev** [comment]
Hi @vitorhugomagalhaes. Yes, I'm still keeping this problem in mind, but I super busy these days. I found reason of problems above and know the solution. If you can make fork and PR with fix - that would be helpful a lot!

So, the problem:
I thought all external (public) methods had synchronised statements, such a 
```
- (id)componentForType:(id)classOrProtocol;

- (id)componentForKey:(NSString *)key args:(TyphoonRuntimeArguments *)args;
```
methods and so on.. But when we using assembly interface to build/access instances, `TyphoonComponentFactory` intercept method invocation and then calls all safe methods from above. So, **problem** is - method invocation interception and handling is not threaded safe :-( 

The solution is:
Wrap content of these method into synchronized statement:
```
TyphoonAssembly.m: forwardInvocation

TyphoonBlockComponentFactory.m: forwardInvocation
TyphoonBlockComponentFactory.m: methodSignatureForSelector
```

Plus I agree with removing static buffer statement. This micro optimisation doesn't worth problems it lead.

And good luck with the release, hope all goes well!

**Comment by vitorhugomagalhaes** [comment]
I've changed the code as requested and submitted the PR.

 I'll be testing our fork during the next week.

Hopefully it won't crash anymore :)

BR,
