### ISSUE TITLE
Twice inject properties

### ISSUE THREAD

**Issue by ct4h** [appsquickly/Typhoon#531]
Typhoon twice inject view controller properties when using Storyboard Reference.
In class TyphoonStoryboard twice call method instantiateViewControllerWithIdentifier: with different identifiers, but return one view controller. 

Example project: https://github.com/ct4h/typhoonEx

Bug repeat in 3.5.1 version open Drawer scene from Authorization scene.

**Comment by etolstoy** [comment]
@ct4h try new `TyphoonStoryboardDefinition`'s introduced in Typhoon v.4. We'll update the documentation soon.
