### ISSUE TITLE
Pure Swift framework?

### ISSUE THREAD

**Issue by CalvHobbes** [appsquickly/Typhoon#536]
My apologies if this has been answered earlier. Your readme indicates you're working on a pure Swift version. Do you know the intended release timelines? 

Thanks!

**Comment by alexgarbarev** [comment]
Hey @CalvHobbes. Yes, PureSwift version coming soon. It's in alpha version state. Would like to be alpha tester and see how it works?

**Comment by ilyapuchka** [comment]
Put me in the list, please! 🤗

**Comment by CalvHobbes** [comment]
Hi there, would've liked to, but as is usually the case, I'm stuck with deadlines et al. I'll keep an eye on the repository though, and hope to use the Swift version soon.  What kind of timelines are you looking at? If a stable release is a month away or so, then I might still be able to take it for a test run.

Thanks!

**Comment by inconnu** [comment]
I'll volunteer to test it out -- I'm just noodling with a personal Swift project and am on the hunt for an IoC framework.

**Comment by fwhenin** [comment]
Would love to be an alpha tester

**Comment by MrS3** [comment]
Hi , put me on the list also.  I can't wait to see how it works.

**Comment by alexgarbarev** [comment]
Ok, @MrS3, @fwhenin, @inconnu, @ilyapuchka it's time try if you dare ;-)
https://github.com/appsquickly/TyphoonSwift
