### ISSUE TITLE
Crash on Swift and Objective-C assemblies collaboration

### ISSUE THREAD

**Issue by Brain89** [appsquickly/Typhoon#537]
Hello.
I have an issue with v4-alpha version. If I try to inject an object from Objective-C assembly inside Swift assembly I receive EXC_BAD_ACCESS.

<img width="843" alt="2016-11-21 15 14 59" src="https://cloud.githubusercontent.com/assets/1902763/20482433/b483fcda-affd-11e6-8d04-d8c8b0a8becb.png">

But everything works fine when two Objective-C assemblies are collaborating.

Here is an example project. Have a look at **ASObjectiveCAssembly** and **SwiftAssembly**. 
[TyphoonV4Test.zip](https://github.com/appsquickly/Typhoon/files/603491/TyphoonV4Test.zip)

**Comment by alexgarbarev** [comment]
Hey @Brain89, what do you mean on "v4-alpha"?

**Comment by alexgarbarev** [comment]
Looking..

**Comment by alexgarbarev** [comment]
To get that working, you should make your property declaration as:

```
dynamic var objectiveCAssembly: ASObjectiveCAssembly!
```

and objective-c method return type change to `id`:

```
@interface ASObjectiveCAssembly : TyphoonAssembly

- (id)objectiveCDefinition;

@end
```

**Comment by alexgarbarev** [comment]
Just checked and confirmed. Sample project doesn't work with stable Typhoon (3.5.1) as well.

**Comment by Brain89** [comment]
It is very strange. I have at least one project in production with the similar code and Typhoon 3.5.x and everything works fine.

**Comment by Brain89** [comment]
Your solution could be simpler: it works if I just add **dynamic**.
