### ISSUE TITLE
Injecting-the-assembly-itself doesn't work 

### ISSUE THREAD

**Issue by Brain89** [appsquickly/Typhoon#538]
Hello.
It is unclear with v4 how to use [Injecting-the-assembly-itself](https://github.com/appsquickly/Typhoon/wiki/What%20can%20be%20Injected#injecting-the-assembly-itself). I am now receiving such kind of error message
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TyphoonAssemblyAccessor <getInstanceFromMyProject>:]: unrecognized selector sent to instance 0x610000244fe0'`

**Comment by jasperblues** [comment]
This issue looks obsolete. @Brain89 in v4, you need to use `self.assembly` rather than `_assembly`
