### ISSUE TITLE
Possible loss of a runtime argument

### ISSUE THREAD

**Issue by drumyantsev** [appsquickly/Typhoon#545]
Hi!

Not sure if it is a Typhoon issue and we can't reproduce it stable, but we don't have any other ideas. Maybe you are familiar with something similar.

We have crashes in HockeyApp because of a nil argument. This argument is obtained in object A, then we check it for nil, and after that it goes to Typhoon. We inject this argument to a initializer of object B, and there it becomes nil, which causes a crash. 

Can it be a Typhoon issue?

**Comment by drumyantsev** [comment]
Sorry, it was our mistake :)

**Comment by alexgarbarev** [comment]
Thanks for the update :-)
