### ISSUE TITLE
Collaborating Assemblies not initialized

### ISSUE THREAD

**Issue by msalmanST** [appsquickly/Typhoon#561]
Hi, 

So I stuck in an issue where I have 3 assemblies, let say appAssembly,uiAssembly and coreAssembly. 'appAssembly' keeps the instance of 'uiAssembly' and 'coreAssembly'. I am using plist to initialize the assemblies and they appears in order 

appAssembly
uiAssembly
coreAssembly
(I also try to change the order in plist but didn't help.

Now I want to inject coreAssembly and uiAssembly in appdelegate, so the code looks like below

 ```
public dynamic func appDelegate() -> Any {
        return TyphoonDefinition.withClass(AppDelegate.self){
            (definition) in

            definition?.injectProperty(#selector(getter: AppDelegate.appUIComponents), with: self.appUICompnents)
            definition?.injectProperty(#selector(getter: AppDelegate.coreComponents), with: self.appCoreComponentsAssembly)
        }
    }
```
My code is crashing while injecting properties in appdelegate. seems appUIComponents and coreComponents objects are not initialized yet.

**Comment by msalmanST** [comment]
I found the issue, I wasn't using the dynamic keyword with the assembly object.

**Comment by jasperblues** [comment]
👍
