### ISSUE TITLE
Documentation warnings

### ISSUE THREAD

**Issue by Emailrus** [appsquickly/Typhoon#564]
Methods in `TyphoonDefinition+Storyboard.h` share one comment and XCode doesn't like discrepancies between param and actual declaration now. Therefore it has a couple of dozens warnings repeating:

```
Warning:(22, 9) parameter 'storyboard' not found in the function declaration
Warning:(24, 9) parameter 'injections' not found in the function declaration
```

**Comment by jasperblues** [comment]
Thanks a lot for reporting. Would you be interested in sending a pull request?

**Comment by Emailrus** [comment]
Maybe a couple of weeks later. Unless someone else will fix it
