### ISSUE TITLE
None of the provided sample code work or compile

### ISSUE THREAD

**Issue by klische** [appsquickly/Typhoon#571]
https://github.com/appsquickly/Typhoon-Swift-Example is outdated by 2 years
https://github.com/appsquickly/Typhoon-example crashes on line 102 in PFApplicationAssembly.m         [definition injectProperty:@selector(theme) with:[_themeProvider currentTheme]]; EXC_BAD_ACCESS

https://github.com/appsquickly/Typhoon/tree/master/TyphoonFrameworkSwiftExample has several issues:

- The macOS target Typhoon-OSX doesn't do anything
- The iOS target crashes on launch in line 28 with Can't resolve assembly for name StoryboardWithReferenceAssembly

**Comment by jasperblues** [comment]
Yeah, this sample is very badly outdated. Needs to be fixed and/or converted to Typhoon Swift (the pure swift version). 

In the meantime, if you have a question, we can help folks. And there's a (smaller) example in the Typhoon codebase.

**Comment by jasperblues** [comment]
Samples were very kindly updated by @atom-wintermute. Thanks again!
