### ISSUE TITLE
How to instance without storyboard？

### ISSUE THREAD

**Issue by FKLam** [appsquickly/Typhoon#577]
From AVc to BVc，but my project had pure code，instaed storyboard.How can I do？

**Comment by jasperblues** [comment]
https://github.com/appsquickly/Typhoon/wiki/What-can-be-Injected#injecting-the-assembly-itself

There's an example of this in the sample app: https://github.com/appsquickly/Typhoon-Swift-Example

**Comment by jasperblues** [comment]
@FKLam please get in touch if you have further questions. StackOverflow is also a good place to ask.
