### ISSUE TITLE
http://www.typhoonframework.org domain name expired or about to be deleted

### ISSUE THREAD

**Issue by sbanil** [appsquickly/Typhoon#580]
I get a message that http://www.typhoonframework.org domain is expired message from Godaddy.com. Looks like domain name is pending renewal.

NOTICE: This domain name expired on 1/11/2018 and is pending renewal or deletion.

**Comment by jasperblues** [comment]
I decided not to renew the domain this year - moved the website to http://appsquickly.github.io/Typhoon/
