### ISSUE TITLE
Not compiled Xcode 9.3

### ISSUE THREAD

**Issue by zarochintsev** [appsquickly/Typhoon#585]
Hi, not compiled  with new Xcode 9.3

<img width="1057" alt="screen shot 2018-04-02 at 14 09 01" src="https://user-images.githubusercontent.com/5650844/38194313-6b80696a-367f-11e8-81e9-2105b2547129.png">

**Comment by atom-wintermute** [comment]
@zarochintsev, This problem fixed in version 4.0.4. You can easily update.

**Comment by zarochintsev** [comment]
@atom-wintermute Nice, thank you!
