### ISSUE TITLE
Flash back crash at startup

### ISSUE THREAD

**Issue by xiubojin** [appsquickly/Typhoon#586]
log:'Can't resolve assembly for name StoryboardWithReferenceAssembly'

**Comment by alexgarbarev** [comment]
hey @xiubojin, StoryboardWithReferenceAssembly - is only included into Typhoon's unit tests target, and shouldn't be mentioned in main target or apps. Can you share more details about the problem? I'll close the issue for now as outdated and will reopen if more details provided.
