### ISSUE TITLE
ios 13 Beta crash

### ISSUE THREAD

**Issue by timur-st94** [appsquickly/typhoon#605]
I just set "Is initial view controller" in Storyboard.

<img width="973" alt="Снимок экрана 2019-07-16 в 14 57 47" src="https://user-images.githubusercontent.com/25498216/61282080-89ea7b00-a7dc-11e9-83c6-5e114d91ac4d.png">

After starting the application crashes

<img width="1425" alt="Снимок экрана 2019-07-16 в 14 47 02" src="https://user-images.githubusercontent.com/25498216/61282219-c3bb8180-a7dc-11e9-998f-11c8dc9b304d.png">

It happens on iOS 13.
If you need any information, let me know.

**Comment by alexgarbarev** [comment]
Good catch.. Can you debug what actually happens there? For example can you just hardcode the `identifier` string and see if it works (so we checking that identifier is correct and memory management is correct for that ivar as well)?

**Comment by timur-st94** [comment]
I just delete isViewLoaded from ATFPreLoade and the application stops crashing. Thanks for the feedback.
