### ISSUE TITLE
Framework target

### ISSUE THREAD

**Issue by ingemarson** [appsquickly/typhoon#609]
Hi,

I would like to use your library in our framework (Objective C), integrated as a static library. We tried to build it, but we ran into some issues. Do you have something like a tutorial or how-to? would be great!

Thanks

**Comment by jasperblues** [comment]
Really sorry for the slow reply. Do you still need this @ingemarson ? 

Btw, last July or so I made some commits to build against latest SDKs. Closing this for now, but please reopen if you still need help. Sorry that we didn't get to you sooner.

**Comment by ingemarson** [comment]
Hi,

no, this is no longer needed. we decided to not use this library even if it looked promising in the beginning. anyhow, thanks for the reply!

**Comment by jasperblues** [comment]
Welcome, take care! 

[Pilgrim](https://github.com/appsquickly/pilgrim) is a pure swift successor to Typhoon.
