### ISSUE TITLE
How to get an instance from Typhoon?

### ISSUE THREAD

**Issue by kornerr** [appsquickly/typhoon#610]
Is there a way to get an instance from TyphoonDefinition?
If not, what's the best way to get the instance out of Typhoon?

**Comment by xv-jasper-b** [comment]
Hello @kornerr !

We use this issue tracker for bugs and feature requests. Question are directed to StackOverflow please. 

Have you read the documentation or tried the sample apps? 

Instances are obtained from an activated assembly.

**Comment by jasperblues** [comment]
Hello @kornerr !

We use this issue tracker for bugs and feature requests. Question are directed to StackOverflow please. 

Have you read the documentation or tried the sample apps? 

Instances are obtained from an activated assembly.
